"""
@module: app.services.geometry.generation
@context: Domain layer — involute gear generation (Verzahnen) by a rack-type tool.
@role: Reproduce, from current-standard involute geometry (DIN ISO 21771), the
       circles that are created when a gear is generated by a hob/rack reference
       profile: the generation profile shift ``x_E`` (ISO 21771 §7.4), the root
       form circle ``d_Ff`` and — when the tool carries an edge-break flank — the
       tip form circle ``d_Fa`` and the radial tip chamfer ``h_K`` (Kopfkanten-
       bruch, ISO 21771 §7.6 eq. 127, ``d_Fa = d_a − 2·(z/|z|)·h_K``).

The tip chamfer is the intersection of two involutes: the usable involute
(Nutz-Evolvente, base ``d·cos α_t``) and the edge-break involute (Kantenbruch-
Evolvente, base ``d·cos α_tK``). That a straight tool flank generates an involute,
and that two involutes meet where their tooth thicknesses are equal, is pure
involute geometry — built here from ISO 21771 primitives only (involute function,
tooth thickness ``s_y`` §6, base circle). The assembled construction was
cross-checked against the historical DIN 3960 §A.3.1 worked form (used for
understanding only; not a computational basis — it is a withdrawn standard).

Validated exactly against STplus for the project gear (kst-E): per gear
``x_E``, ``d_Ff``, ``d_Fa``, ``h_K`` and the rest tip thickness ``s_aK``.

Convention: external gears (``z > 0``); a gear with no edge-break flank has
``d_Fa = d_a`` and ``h_K = 0``.
"""

import math
from collections.abc import Callable

from pydantic import BaseModel

from app.io.ste import SteGearStage, SteToolProfile


def involute(angle_rad: float) -> float:
    """Involute function inv(alpha) = tan(alpha) - alpha (radians)."""
    return math.tan(angle_rad) - angle_rad


def inverse_involute(value: float, *, guess_rad: float = 0.35) -> float:
    """Solve inv(alpha) = ``value`` for alpha (radians) by Newton iteration."""
    alpha = guess_rad
    for _ in range(60):
        delta = (math.tan(alpha) - alpha - value) / math.tan(alpha) ** 2
        alpha -= delta
        if abs(delta) < 1e-14:
            break
    return alpha


def _bisect(func: Callable[[float], float], lo: float, hi: float, *, iters: int = 100) -> float:
    """Bisection root of a sign-changing ``func`` on ``[lo, hi]`` (no SciPy dependency)."""
    f_lo = func(lo)
    for _ in range(iters):
        mid = 0.5 * (lo + hi)
        f_mid = func(mid)
        if f_lo * f_mid <= 0.0:
            hi = mid
        else:
            lo, f_lo = mid, f_mid
        if hi - lo < 1e-12:
            break
    return 0.5 * (lo + hi)


class ToolReferenceProfile(BaseModel):
    """A rack/hob tool reference profile; height factors refer to ``m_n0``.

    The pre-cutting tool that generates the gear. Its addendum (with tip rounding)
    cuts the gear root and sets ``d_Ff``; an edge-break flank on its dedendum
    (``root_form_height_factor < dedendum_factor``) cuts the tip chamfer.
    """

    addendum_factor: float  # h_aP0*
    tip_radius_factor: float = 0.0  # rho_aP0*
    dedendum_factor: float | None = None  # h_fP0*
    root_form_height_factor: float | None = None  # h_FfP0*
    normal_pressure_angle_deg: float = 20.0  # alfa_n0
    edge_break_angle_deg: float | None = None  # alfa_Kn0

    @property
    def has_tip_chamfer(self) -> bool:
        """True if the dedendum carries an edge-break flank that cuts a tip chamfer."""
        return (
            self.edge_break_angle_deg is not None
            and self.root_form_height_factor is not None
            and self.dedendum_factor is not None
            and self.root_form_height_factor < self.dedendum_factor
        )

    @classmethod
    def from_ste(
        cls, tool: SteToolProfile, *, fallback_pressure_angle_deg: float
    ) -> "ToolReferenceProfile":
        """Build from a parsed `.ste` tool section, defaulting the pressure angle to the gear's."""
        return cls(
            addendum_factor=tool.addendum_factor if tool.addendum_factor is not None else 1.25,
            tip_radius_factor=tool.tip_radius_factor or 0.0,
            dedendum_factor=tool.dedendum_factor,
            root_form_height_factor=tool.root_form_height_factor,
            normal_pressure_angle_deg=(
                tool.pressure_angle_deg
                if tool.pressure_angle_deg is not None
                else fallback_pressure_angle_deg
            ),
            edge_break_angle_deg=tool.edge_break_angle_deg,
        )


class GearGeneration(BaseModel):
    """One generated gear: its tool-cut form circles and tip chamfer.

    All angles in degrees on input; lengths in mm. The transverse plane is used
    throughout; for spur gears (``beta = 0``) transverse equals normal.
    """

    normal_module_mm: float
    teeth: int
    normal_pressure_angle_deg: float = 20.0
    helix_angle_deg: float = 0.0
    profile_shift: float = 0.0
    tip_diameter_mm: float
    tool: ToolReferenceProfile
    tooth_width_allowance_mm: float = 0.0  # mean A_We (span allowance), drives x_E

    @property
    def _beta(self) -> float:
        return math.radians(self.helix_angle_deg)

    @property
    def _alpha_n(self) -> float:
        return math.radians(self.normal_pressure_angle_deg)

    @property
    def _alpha_t(self) -> float:
        return math.atan(math.tan(self._alpha_n) / math.cos(self._beta))

    @property
    def transverse_module_mm(self) -> float:
        return self.normal_module_mm / math.cos(self._beta)

    @property
    def reference_diameter_mm(self) -> float:
        return self.transverse_module_mm * self.teeth

    @property
    def base_diameter_mm(self) -> float:
        return self.reference_diameter_mm * math.cos(self._alpha_t)

    @property
    def generation_profile_shift(self) -> float:
        """Generation profile shift x_E (ISO 21771 §7.4): nominal x plus the mean
        tooth-thickness allowance A_sn = A_We / cos(alpha_n)."""
        allowance_sn = self.tooth_width_allowance_mm / math.cos(self._alpha_n)
        return self.profile_shift + allowance_sn / (
            2.0 * self.normal_module_mm * math.tan(self._alpha_n)
        )

    @property
    def _tooth_thickness_transverse_mm(self) -> float:
        """As-cut transverse tooth thickness at the reference circle (uses x_E)."""
        return (
            self.transverse_module_mm * math.pi / 2.0
            + 2.0 * self.generation_profile_shift * self.normal_module_mm * math.tan(self._alpha_t)
        )

    @property
    def _half_tooth_angle_base(self) -> float:
        """Half tooth angle at the base circle for the usable (Nutz) involute."""
        return self._tooth_thickness_transverse_mm / self.reference_diameter_mm + involute(
            self._alpha_t
        )

    @property
    def root_form_diameter_mm(self) -> float:
        """Root form circle d_Ff: where the usable involute ends at the tool tip rounding."""
        x_e_mm = self.generation_profile_shift * self.normal_module_mm
        tip_form_height = (
            self.tool.addendum_factor
            - self.tool.tip_radius_factor
            * (1.0 - math.sin(math.radians(self.tool.normal_pressure_angle_deg)))
        ) * self.normal_module_mm
        radius = self.reference_diameter_mm / 2.0
        line_of_action = (tip_form_height - x_e_mm) / math.sin(self._alpha_t)
        base_radius = self.base_diameter_mm / 2.0
        return 2.0 * math.hypot(base_radius, radius * math.sin(self._alpha_t) - line_of_action)

    @property
    def _edge_break_alpha_t(self) -> float:
        """Transverse profile angle of the edge-break flank (only valid with a chamfer)."""
        angle = self.tool.edge_break_angle_deg
        assert angle is not None  # guaranteed by has_tip_chamfer at call sites
        return math.atan(math.tan(math.radians(angle)) / math.cos(self._beta))

    @property
    def _edge_break_base_diameter_mm(self) -> float:
        return self.reference_diameter_mm * math.cos(self._edge_break_alpha_t)

    @property
    def _edge_break_half_tooth_angle_base(self) -> float:
        """Half tooth angle at the base of the edge-break (Kantenbruch) involute.

        Its transverse tooth thickness references the edge-break angle: the last
        term uses ``tan α_tK`` (not ``tan α_t``).
        """
        alpha_tk = self._edge_break_alpha_t
        root_form_factor = self.tool.root_form_height_factor
        assert root_form_factor is not None  # guaranteed by has_tip_chamfer
        root_form_height = root_form_factor * self.normal_module_mm
        x_e_mm = self.generation_profile_shift * self.normal_module_mm
        tooth_thickness_k = (
            self.transverse_module_mm * math.pi / 2.0
            + 2.0 * root_form_height * (math.tan(alpha_tk) - math.tan(self._alpha_t))
            + 2.0 * x_e_mm * math.tan(alpha_tk)
        )
        return tooth_thickness_k / self.reference_diameter_mm + involute(alpha_tk)

    @property
    def tip_form_diameter_mm(self) -> float:
        """Tip form circle d_Fa = intersection of the usable and edge-break involutes.

        Without an edge-break flank the usable involute runs to the tip circle, so
        d_Fa = d_a (no chamfer).
        """
        if not self.tool.has_tip_chamfer:
            return self.tip_diameter_mm
        base = self.base_diameter_mm
        base_k = self._edge_break_base_diameter_mm
        psi_b = self._half_tooth_angle_base
        psi_bk = self._edge_break_half_tooth_angle_base

        def condition(d_fa: float) -> float:
            alpha_fa = math.acos(base / d_fa)
            alpha_kfa = math.acos(base_k / d_fa)
            return psi_bk - psi_b - involute(alpha_kfa) + involute(alpha_fa)

        return _bisect(condition, base * (1.0 + 1e-9), self.tip_diameter_mm)

    @property
    def tip_chamfer_radial_mm(self) -> float:
        """Radial height of the tip chamfer h_K = (d_a − d_Fa) / 2 (ISO 21771 eq. 127)."""
        return (self.tip_diameter_mm - self.tip_form_diameter_mm) / 2.0

    @property
    def rest_tip_thickness_mm(self) -> float:
        """Transverse tip thickness at d_a; reduced by the edge-break when present (Restkopfdicke).

        Tooth thickness of an involute at a diameter (ISO 21771 §6): ``s_y =
        d_y·(psi_b − inv α_y)``. With an edge-break flank the tip thickness follows
        the edge-break (Kantenbruch) involute, otherwise the usable involute.
        """
        if not self.tool.has_tip_chamfer:
            alpha_a = math.acos(self.base_diameter_mm / self.tip_diameter_mm)
            return self.tip_diameter_mm * (self._half_tooth_angle_base - involute(alpha_a))
        alpha_ak = math.acos(self._edge_break_base_diameter_mm / self.tip_diameter_mm)
        return self.tip_diameter_mm * (self._edge_break_half_tooth_angle_base - involute(alpha_ak))

    @classmethod
    def from_ste_gear(cls, stage: SteGearStage, index: int) -> "GearGeneration":
        """Build the generation model for gear ``index`` (0 = pinion, 1 = wheel).

        Requires the tip diameter and the generating tool profile in the `.ste`.
        """
        if stage.tip_diameter_mm is None:
            raise ValueError("'.ste' has no KOPFKREISDM; tip diameter is required for generation")
        if stage.tools is None or stage.tools[index] is None:
            raise ValueError("'.ste' has no tool profile for this gear (WERKZEUG_VORVERZ.)")
        tool = stage.tools[index]
        assert tool is not None  # narrowed by the guard above
        allowance_mm = 0.0
        upper = stage.tooth_width_allowance_upper_um
        lower = stage.tooth_width_allowance_lower_um
        if upper is not None and lower is not None:
            allowance_mm = (upper[index] + lower[index]) / 2.0 / 1000.0
        return cls(
            normal_module_mm=stage.normal_module_mm,
            teeth=stage.teeth[index],
            normal_pressure_angle_deg=stage.pressure_angle_deg[index],
            helix_angle_deg=stage.helix_angle_deg[index],
            profile_shift=stage.profile_shift[index],
            tip_diameter_mm=stage.tip_diameter_mm[index],
            tool=ToolReferenceProfile.from_ste(
                tool, fallback_pressure_angle_deg=stage.pressure_angle_deg[index]
            ),
            tooth_width_allowance_mm=allowance_mm,
        )
