"""gearcore — norm-traceable involute cylindrical gear geometry with pydantic contracts.

Stage 1 (2026-09-28 restart): the 2D geometry chain for external spur and helical gears
generated by rack-type tools, verified against norm worked examples and the STplus oracle.
Every computational function carries an ``@eq`` reference to its primary source
(norm + edition, equation, section, page); see ``gearcore.trace``.
"""

from gearcore.errors import (
    GearCoreError,
    GeometryInfeasibleError,
    InputRangeError,
    NotSupportedError,
    ParseError,
    SolverError,
)
from gearcore.models.common import DimensionLimits, FrozenModel, InputWarning, Pair
from gearcore.models.inputs import (
    BallMeasurement,
    DimensionKind,
    GearInput,
    GearKind,
    MaterialKind,
    MaterialRef,
    PairInput,
    SpanMeasurement,
    ToolKind,
    ToolProfile,
)

__version__ = "2.0.0a0"

__all__ = [
    "BallMeasurement",
    "DimensionKind",
    "DimensionLimits",
    "FrozenModel",
    "GearCoreError",
    "GearInput",
    "GearKind",
    "GeometryInfeasibleError",
    "InputRangeError",
    "InputWarning",
    "MaterialKind",
    "MaterialRef",
    "NotSupportedError",
    "Pair",
    "PairInput",
    "ParseError",
    "SolverError",
    "SpanMeasurement",
    "ToolKind",
    "ToolProfile",
    "__version__",
]
