"""Tool-based generation of an external cylindrical gear by a rack-type tool.

Sources: DIN ISO 21771:2014-08 (ISO 21771:2007) §4.6 heights, §4.7 tooth thickness with x_E,
§7.1 tool reference profile, §7.3 tooth thickness allowances, §7.4 generating profile shift,
§7.5 generated root diameter, §7.6 form circles (Eq. (128) in the corrected form of Anhang NB,
p. 6), §7.7 undercut, §7.9 tip tooth thickness; DIN 3960:1987-03 Anhang A.3.1 for the tip form
circle generated by the edge break flank of the tool, which the current norm does not give; FVA
604 I (2012) for the straight part of the tool addendum. Every function realises one equation;
angles are radians (``_rad``), lengths millimetres (``_mm``), the allowance micrometres
(``_um``) like the contract. Formulas are written for external gears.

Which value of x_E. The allowances give two generating profile shift coefficients, x_Es at the
upper and x_Ei at the lower tooth thickness allowance (Eq. (123), (124); Bild 38 letters
d_fEs and d_fEi). The generation is evaluated at x_Es (the maximum-material tooth, as STplus
prints it) and reports x_Ei and d_fEi alongside. Without allowances x_E = x and the result says
so. §7.5 asks for the values of the finishing process: a machining allowance q of the tool
(Eq. (120), (121)) belongs to a pre-machining tool whose fillet is finished by a second tool; the
finishing tool is an extension point, so a tool with q > 0 is not supported here, nor is a tool
with a protuberance (DIN 3960 A.3.3) or a tool whose module or profile angle differs from the
gear's (generating gear with alpha_wt0, Bild 39 note).

Root form circle. Eq. (128) holds for a gear free of undercut. The undercut limit is Eq. (135):
x_E < x_Emin means that the straight part of the tool flank reaches beyond the tangent point T of
the line of action; the root form circle is then the intersection of the fillet with the
involute (§7.6, p. 70), found numerically in ``gearcore.trochoid``. Eq. (129)/(130) are kept as a
cross-check; as printed, Eq. (130) uses sin(alpha_t) inside the bracket where Anhang NB corrects
Eq. (128) to sin(alpha_n), so the two agree for spur gears only (finding of increment 3).

Tip form circle. A tip chamfer given as an input is defined by h_K and s_aK (§6.1.2, Bild 24):
d_Fa = d_a - 2 h_K (Eq. (127)). A tool with an edge break flank (angle alpha_kP from the height
h_FfP0 above the datum line, Bild 36 a)) generates a second involute at the tip; the tip form
circle is the intersection of the two involutes (DIN 3960 Eq. (A.3.06)), the residual tooth
thickness at the tip Eq. (A.3.05). The short trochoid of the corner of the tool profile between
the two involutes is not modelled, as in DIN 3960.

Tolerance at boundaries. ``EPS`` (relative) as in ``gearcore.pair``: a value of Eq. (128) whose
bracket is negative by rounding noise only is the base circle; the edge break involute reaches
the tip only if it is thinner there by more than rounding noise.
"""

import math

from scipy.optimize import brentq

from gearcore import involute as iv
from gearcore import pair as pr
from gearcore import trochoid as tr
from gearcore._guards import HALF_PI, helix, pressure_angle, teeth
from gearcore._safe import EPS, finite_input, finite_result, positive_input, safe_div
from gearcore.errors import GeometryInfeasibleError, InputRangeError, NotSupportedError
from gearcore.models.common import InputWarning, Pair
from gearcore.models.inputs import GearInput, PairInput, ToolKind, ToolProfile
from gearcore.models.results import GearGeneration, GenerationResult
from gearcore.rack import has_edge_break_flank
from gearcore.trace import eq

SOURCE = "ISO21771:2014"
OLD = "DIN3960:1987"
FVA = "FVA604-I:2012"

EQ_EXEMPT = ("compute_generation",)
"""The orchestrator assembles results from traced functions and carries no equation of its own."""

ROLES = ("pinion", "wheel")
SAME_TOOL_TOLERANCE = 1.0e-6
"""Relative tolerance within which a tool module or profile angle is that of the gear (the
contract admits a tool that generates the same basic rack within this tolerance)."""


# --- §7.3, §7.4 tooth thickness allowances and generating profile shift ------------------------


@eq(SOURCE, "(118)", section="7.3", page=65)
@eq(SOURCE, "(119)", section="7.3", page=65)
def tooth_thickness_limit(s_n_mm: float, tooth_thickness_allowance_um: float) -> float:
    """Upper or lower limit of the normal tooth thickness: s_ns = s_n + E_sns, s_ni = s_n + E_sni.

    The allowance is given in micrometres like the contract; the result is in millimetres.
    """
    s_n = finite_input(s_n_mm, "normal tooth thickness s_n")
    allowance = finite_input(tooth_thickness_allowance_um, "tooth thickness allowance E_sn")
    return finite_result(s_n + 1.0e-3 * allowance, "tooth thickness limit")


@eq(SOURCE, "(123)", section="7.4", page=67)
@eq(SOURCE, "(124)", section="7.4", page=67)
@eq(OLD, "(3.6.03)", section="3.6.3", page=14, note="with q = 0; A_s of DIN 3960 is E_sn")
def generating_profile_shift_coefficient(
    x: float, m_n_mm: float, alpha_n_rad: float, tooth_thickness_allowance_um: float
) -> float:
    """Generating profile shift coefficient of a finished gear (q = 0):
    x_E = x + E_sn / (2 m_n tan(alpha_n)).

    Eq. (123) with the upper allowance E_sns gives x_Es, Eq. (124) with the lower allowance E_sni
    gives x_Ei. The allowance is the normal tooth thickness allowance in micrometres.
    """
    shift = finite_input(x, "profile shift coefficient x")
    m_n = positive_input(m_n_mm, "normal module m_n")
    alpha_n = pressure_angle(alpha_n_rad, "normal pressure angle alpha_n")
    allowance = 1.0e-3 * finite_input(
        tooth_thickness_allowance_um, "tooth thickness allowance E_sn"
    )
    return finite_result(
        shift
        + safe_div(allowance, 2.0 * m_n * math.tan(alpha_n), what="E_sn / (2 m_n tan alpha_n)"),
        "generating profile shift coefficient x_E",
    )


@eq(
    SOURCE,
    "(120)",
    section="7.4",
    page=67,
    note="q_max = q_min = q: one allowance of the pre-machining tool",
)
@eq(SOURCE, "(121)", section="7.4", page=67)
@eq(OLD, "(3.6.03)", section="3.6.3", page=14, note="term q / sin(alpha_n)")
def pre_machining_generating_profile_shift_coefficient(
    x_E: float, m_n_mm: float, alpha_n_rad: float, q_mm: float
) -> float:
    """Generating profile shift coefficient of the pre-machining tool that leaves the machining
    allowance q per flank: x_EV = x_E + q / (m_n sin(alpha_n)).

    Eq. (120) and (121) pair the limits (x_EsV with x_Ei and q_max, x_EiV with x_Es and q_min);
    with one allowance q of the tool both read as above. The root generated by the pre-machining
    tool and the flank finished at x_E give the gear of Bild 36 b).
    """
    shift = finite_input(x_E, "generating profile shift coefficient x_E")
    m_n = positive_input(m_n_mm, "normal module m_n")
    alpha_n = pressure_angle(alpha_n_rad, "normal pressure angle alpha_n")
    q = finite_input(q_mm, "machining allowance q")
    if q < 0.0:
        raise InputRangeError(f"machining allowance q must be >= 0, got {q_mm!r}")
    return finite_result(
        shift + safe_div(q, m_n * math.sin(alpha_n), what="q / (m_n sin alpha_n)"), "x_EV"
    )


# --- §7.1, §7.5, §7.6, §7.7 tool addendum, generated root, root form circle, undercut --------------


@eq(
    SOURCE,
    "(128)",
    section="7.6",
    page=6,
    note="bracket h_aP0 - x_E m_n - rho_aP0 (1 - sin alpha_n) of Anhang NB without x_E m_n; Bild 36 a) p. 64",
)
@eq(FVA, "(4.36)", page=29)
@eq(
    FVA,
    "(4.37)",
    page=29,
    note="with f_pr = 0 (no protuberance): h_prP0 = rho_aP0 (1 - sin alpha_n0)",
)
def tool_tip_form_height(h_aP0_mm: float, rho_aP0_mm: float, alpha_n_rad: float) -> float:
    """Straight part of the tool addendum: h_FaP0 = h_aP0 - rho_aP0 (1 - sin(alpha_n)).

    The tip rounding of radius rho_aP0 touches the flank rho_aP0 (1 - sin alpha_n) above the tip
    line. A rounding that consumes the whole addendum leaves no straight flank
    (``GeometryInfeasibleError``).
    """
    h_aP0 = positive_input(h_aP0_mm, "tool addendum h_aP0")
    rho = finite_input(rho_aP0_mm, "tool tip radius rho_aP0")
    if rho < 0.0:
        raise InputRangeError(f"tool tip radius rho_aP0 must be >= 0, got {rho_aP0_mm!r}")
    alpha_n = pressure_angle(alpha_n_rad, "normal pressure angle alpha_n")
    height = finite_result(h_aP0 - rho * (1.0 - math.sin(alpha_n)), "h_FaP0")
    if height <= 0.0:
        raise GeometryInfeasibleError(
            f"tool tip radius rho_aP0 = {rho!r} leaves no straight flank on the tool addendum "
            f"h_aP0 = {h_aP0!r} (h_FaP0 = {height!r})"
        )
    return height


@eq(SOURCE, "(125)", section="7.5", page=68)
@eq(OLD, "(3.6.04)", section="3.6.4", page=14)
def generated_root_diameter(d_mm: float, x_E: float, m_n_mm: float, h_aP0_mm: float) -> float:
    """Root diameter generated by a rack-type tool: d_fE = d + 2 x_E m_n - 2 h_aP0."""
    d = positive_input(d_mm, "reference diameter d")
    shift = finite_input(x_E, "generating profile shift coefficient x_E")
    m_n = positive_input(m_n_mm, "normal module m_n")
    h_aP0 = positive_input(h_aP0_mm, "tool addendum h_aP0")
    d_fE = finite_result(d + 2.0 * shift * m_n - 2.0 * h_aP0, "generated root diameter d_fE")
    if d_fE <= 0.0:
        raise GeometryInfeasibleError(f"generated root diameter d_fE = {d_fE!r} is not positive")
    return d_fE


@eq(SOURCE, "(135)", section="7.7", page=70)
@eq(OLD, "(3.6.06)", section="3.6.6", page=14)
def min_generating_profile_shift_coefficient(
    h_FaP0_mm: float, m_n_mm: float, z: int, alpha_t_rad: float, beta_rad: float
) -> float:
    """Smallest generating profile shift coefficient free of undercut, for a rack-type tool
    without protuberance: x_Emin = h_FaP0 / m_n - z sin^2(alpha_t) / (2 cos(beta)).

    Below it the straight part of the tool flank reaches beyond the tangent point T of the line of
    action and the tip rounding cuts into the involute.
    """
    h_FaP0 = positive_input(h_FaP0_mm, "tool tip form height h_FaP0")
    m_n = positive_input(m_n_mm, "normal module m_n")
    number = teeth(z)
    alpha_t = pressure_angle(alpha_t_rad, "transverse pressure angle alpha_t")
    beta = helix(beta_rad)
    return finite_result(
        h_FaP0 / m_n - number * math.sin(alpha_t) ** 2 / (2.0 * math.cos(beta)), "x_Emin"
    )


@eq(
    SOURCE,
    "(128)",
    section="7.6",
    page=6,
    note="corrected form of Anhang NB: (1 - sin alpha_n) in the bracket; p. 69 prints (1 - sin alpha_t)",
)
@eq(OLD, "(3.6.08)", section="3.6.7", page=16)
@eq(FVA, "(4.35)", page=29)
def root_form_diameter(
    d_mm: float, alpha_t_rad: float, h_FaP0_mm: float, x_E: float, m_n_mm: float, d_b_mm: float
) -> float:
    """Root form diameter of a gear free of undercut, generated by a rack-type tool:
    d_Ff = sqrt((d sin(alpha_t) - 2 (h_FaP0 - x_E m_n) / sin(alpha_t))^2 + d_b^2),
    with the straight part of the tool addendum h_FaP0 = h_aP0 - rho_aP0 (1 - sin alpha_n).

    The bracket is the roll length from the tangent point T to the point generated by the end of
    the straight flank. A negative bracket means undercut: the equation does not apply and the
    root form circle follows from the intersection of the fillet with the involute
    (``GeometryInfeasibleError``; see ``compute_generation``). Within ``EPS`` d of zero the
    bracket is zero and d_Ff = d_b.
    """
    d = positive_input(d_mm, "reference diameter d")
    alpha_t = pressure_angle(alpha_t_rad, "transverse pressure angle alpha_t")
    h_FaP0 = positive_input(h_FaP0_mm, "tool tip form height h_FaP0")
    shift = finite_input(x_E, "generating profile shift coefficient x_E")
    m_n = positive_input(m_n_mm, "normal module m_n")
    d_b = positive_input(d_b_mm, "base diameter d_b")
    sine = math.sin(alpha_t)
    roll = finite_result(
        d * sine - safe_div(2.0 * (h_FaP0 - shift * m_n), sine, what="(128)"), "roll length"
    )
    if roll < -EPS * d:
        raise GeometryInfeasibleError(
            f"undercut: the straight flank of the tool reaches {-0.5 * roll!r} mm beyond the "
            "tangent point T; Eq. (128) does not apply, the root form circle is the intersection "
            "of the fillet with the involute"
        )
    return finite_result(math.hypot(max(roll, 0.0), d_b), "root form diameter d_Ff")


@eq(SOURCE, "(129)", section="7.6", page=69)
@eq(
    SOURCE,
    "(130)",
    section="7.6",
    page=69,
    note="as printed, with (1 - sin alpha_t): agrees with the corrected Eq. (128) for spur gears only",
)
@eq(OLD, "(3.6.09)", section="3.6.7", page=16)
@eq(OLD, "(3.6.10)", section="3.6.7", page=16, note="prints h*_FaP0 in place of the bracket")
def root_form_diameter_by_roll_angle(
    d_b_mm: float,
    z: int,
    alpha_t_rad: float,
    beta_rad: float,
    h_aP0_mm: float,
    rho_aP0_mm: float,
    m_n_mm: float,
    x_E: float,
) -> float:
    """Root form diameter by the roll angle at the root form circle, as printed:
    tan(alpha_Ff) = xi_Ff = xi_t - 4 [(h_aP0 - rho_aP0 (1 - sin alpha_t)) / m_n - x_E] cos(beta)
    / (z sin(2 alpha_t)), d_Ff = d_b / cos(alpha_Ff).

    Cross-check of Eq. (128) for spur gears. For helical gears the printed sine of alpha_t in the
    bracket differs from the corrected Eq. (128) of Anhang NB (sin alpha_n); this function keeps
    the printed form so that the difference can be shown. A negative roll angle means undercut
    (``GeometryInfeasibleError``).
    """
    d_b = positive_input(d_b_mm, "base diameter d_b")
    number = teeth(z)
    alpha_t = pressure_angle(alpha_t_rad, "transverse pressure angle alpha_t")
    beta = helix(beta_rad)
    h_aP0 = positive_input(h_aP0_mm, "tool addendum h_aP0")
    rho = finite_input(rho_aP0_mm, "tool tip radius rho_aP0")
    m_n = positive_input(m_n_mm, "normal module m_n")
    shift = finite_input(x_E, "generating profile shift coefficient x_E")
    bracket = (h_aP0 - rho * (1.0 - math.sin(alpha_t))) / m_n - shift
    xi = finite_result(
        math.tan(alpha_t) - 4.0 * bracket * math.cos(beta) / (number * math.sin(2.0 * alpha_t)),
        "roll angle xi_Ff",
    )
    if xi < -EPS:
        raise GeometryInfeasibleError(
            f"undercut: the roll angle at the root form circle xi_Ff = {xi!r} is negative"
        )
    return finite_result(d_b / math.cos(math.atan(max(xi, 0.0))), "root form diameter d_Ff")


# --- §7.6 tip form circle -------------------------------------------------------------------------


@eq(SOURCE, "(127)", section="7.6", page=68, note="solved for h_K")
def tip_chamfer_height(d_a_mm: float, d_Fa_mm: float) -> float:
    """Radial height of the tip chamfer from the tip form diameter: h_K = (d_a - d_Fa) / 2."""
    d_a = positive_input(d_a_mm, "tip diameter d_a")
    d_Fa = positive_input(d_Fa_mm, "tip form diameter d_Fa")
    if d_Fa > d_a * (1.0 + EPS):
        raise InputRangeError(f"tip form diameter {d_Fa!r} exceeds the tip diameter {d_a!r}")
    return max(0.5 * (d_a - d_Fa), 0.0)


@eq(
    SOURCE,
    "(14)",
    section="4.3.6",
    page=30,
    note="for the edge break flank of the tool: tan alpha_tK = tan alpha_kP / cos beta (DIN 3960 Anhang A)",
)
def edge_break_transverse_angle(alpha_kP_rad: float, beta_rad: float) -> float:
    """Transverse profile angle of the edge break flank of the tool."""
    alpha_kP = pressure_angle(alpha_kP_rad, "edge break angle alpha_kP")
    if alpha_kP <= 0.0:
        raise InputRangeError("edge break angle alpha_kP must be > 0")
    return iv.transverse_pressure_angle(alpha_kP, beta_rad)


@eq(
    SOURCE,
    "(19)",
    section="4.3.10",
    page=31,
    note="base diameter of the edge break involute, d_bK = d cos alpha_tK (DIN 3960 Anhang A, p. 51)",
)
def edge_break_base_diameter(d_mm: float, alpha_tK_rad: float) -> float:
    """Base diameter of the involute generated by the edge break flank: d_bK = d cos(alpha_tK)."""
    d = positive_input(d_mm, "reference diameter d")
    return finite_result(d * math.cos(pressure_angle(alpha_tK_rad, "alpha_tK")), "d_bK")


@eq(OLD, "(A.3.03)", section="A.3.1", page=52)
def edge_break_transverse_tooth_thickness(
    m_n_mm: float,
    beta_rad: float,
    h_FfP0_mm: float,
    alpha_t_rad: float,
    alpha_tK_rad: float,
    x_E: float,
) -> float:
    """Transverse tooth thickness at the reference circle of the edge break involute:
    (x_E is that of the tool carrying the edge break flank, DIN 3960 Bild A.2/A.3: x_EV for a
    pre-machining tool with q > 0, which is not generated here, so x_E = x_Es)
    s_tK = m_t pi / 2 + 2 h_FfP0 (tan(alpha_tK) - tan(alpha_t)) + 2 x_E m_n tan(alpha_tK).

    The edge break flank of the tool starts h_FfP0 above the datum line; extended to the datum
    line it leaves the wider space of the first term (the tool space narrows faster above the
    kink, so the tooth is thinner at the tip).
    """
    m_n = positive_input(m_n_mm, "normal module m_n")
    beta = helix(beta_rad)
    h_FfP0 = finite_input(h_FfP0_mm, "tool root form height h_FfP0")
    if h_FfP0 < 0.0:
        raise InputRangeError(f"tool root form height h_FfP0 must be >= 0, got {h_FfP0_mm!r}")
    alpha_t = pressure_angle(alpha_t_rad, "transverse pressure angle alpha_t")
    alpha_tK = pressure_angle(alpha_tK_rad, "alpha_tK")
    if alpha_tK <= alpha_t:
        raise InputRangeError(
            f"the edge break flank must be steeper than the flank: alpha_tK = "
            f"{math.degrees(alpha_tK)!r} deg <= alpha_t = {math.degrees(alpha_t)!r} deg"
        )
    shift = finite_input(x_E, "generating profile shift coefficient x_E")
    m_t = iv.transverse_module(m_n, beta)
    return finite_result(
        m_t * HALF_PI
        + 2.0 * h_FfP0 * (math.tan(alpha_tK) - math.tan(alpha_t))
        + 2.0 * shift * m_n * math.tan(alpha_tK),
        "s_tK",
    )


@eq(
    OLD,
    "(A.3.03)",
    section="A.3.1",
    page=52,
    note="right-hand side: s_tK = d (psi_bK - inv alpha_tK)",
)
def edge_break_base_half_angle(s_tK_mm: float, d_mm: float, alpha_tK_rad: float) -> float:
    """Base tooth thickness half angle of the edge break involute: psi_bK = s_tK / d + inv(alpha_tK)."""
    s_tK = finite_input(s_tK_mm, "s_tK")
    return s_tK / positive_input(d_mm, "reference diameter d") + iv.inv(alpha_tK_rad)


def _thickness_gap(
    d_mm: float, d_b_mm: float, d_bK_mm: float, psi_b_rad: float, psi_bK_rad: float
) -> float:
    """psi_bK - psi_b - inv(alpha_tKFa) + inv(alpha_tFa) at the diameter d: positive where the
    edge break involute is the thicker one (Eq. (A.3.02), (A.3.04) divided by d)."""
    alpha = iv.transverse_profile_angle_at(d_mm, d_b_mm)
    alpha_K = iv.transverse_profile_angle_at(d_mm, d_bK_mm)
    return psi_bK_rad - psi_b_rad - iv.inv(alpha_K) + iv.inv(alpha)


@eq(OLD, "(A.3.06)", section="A.3.1", page=52)
@eq(OLD, "(A.3.02)", section="A.3.1", page=52)
@eq(OLD, "(A.3.04)", section="A.3.1", page=52)
def tip_form_diameter_from_edge_break(
    d_b_mm: float, d_bK_mm: float, psi_b_rad: float, psi_bK_rad: float, d_a_mm: float
) -> float:
    """Tip form diameter generated by the edge break flank of the tool: the diameter at which the
    involute and the edge break involute have the same tooth thickness,
    psi_bK - psi_b - inv(alpha_tKFa) + inv(alpha_tFa) = 0 (iteration between d_b and d_a).

    Returns d_a where the edge break involute is not thinner than the involute at the tip (the
    edge break flank does not reach the tip: no chamfer). Raises ``GeometryInfeasibleError`` where
    the edge break involute is thinner over the whole flank.
    """
    d_b = positive_input(d_b_mm, "base diameter d_b")
    d_bK = positive_input(d_bK_mm, "base diameter of the edge break involute d_bK")
    d_a = positive_input(d_a_mm, "tip diameter d_a")
    if d_bK >= d_b:
        raise InputRangeError(
            f"the edge break involute needs the smaller base circle: d_bK = {d_bK!r} >= d_b = {d_b!r}"
        )
    psi_b = finite_input(psi_b_rad, "psi_b")
    psi_bK = finite_input(psi_bK_rad, "psi_bK")
    if d_a <= d_b:
        raise GeometryInfeasibleError(
            f"tip diameter {d_a!r} does not lie above the base circle {d_b!r}"
        )
    at_tip = _thickness_gap(d_a, d_b, d_bK, psi_b, psi_bK)
    if at_tip >= -EPS:
        return d_a
    at_base = _thickness_gap(d_b, d_b, d_bK, psi_b, psi_bK)
    if at_base <= 0.0:
        raise GeometryInfeasibleError(
            "the edge break involute of the tool is thinner than the involute down to the base "
            "circle: no tip form circle (tool root form height h_FfP0 too small or edge break "
            "angle too large)"
        )
    d_Fa = brentq(
        lambda d: _thickness_gap(d, d_b, d_bK, psi_b, psi_bK), d_b, d_a, xtol=1e-13, rtol=1e-15
    )
    return finite_result(float(d_Fa), "tip form diameter d_Fa")


@eq(OLD, "(A.3.05)", section="A.3.1", page=52)
def residual_tip_thickness(d_a_mm: float, d_bK_mm: float, psi_bK_rad: float) -> float:
    """Residual tooth thickness at the tip circle on the edge break involute (transverse):
    s_aK = d_a (psi_bK - inv(alpha_taK)), cos(alpha_taK) = d_bK / d_a."""
    d_a = positive_input(d_a_mm, "tip diameter d_a")
    alpha = iv.transverse_profile_angle_at(d_a, positive_input(d_bK_mm, "d_bK"))
    psi = finite_input(psi_bK_rad, "psi_bK") - iv.inv(alpha)
    if psi <= 0.0:
        raise GeometryInfeasibleError(
            "the edge break involutes of both flanks intersect below the tip circle (s_aK = "
            f"{d_a * psi!r}): the tooth is pointed by the chamfer; a smaller tip diameter is "
            "needed (STplus cuts the tip circle to the diameter where the flanks meet)"
        )
    return finite_result(d_a * psi, "residual tip thickness s_aK")


# --- §4.6, §4.7 heights and tip tooth thickness ---------------------------------------------------


@eq(
    SOURCE,
    "(35)",
    section="4.6.1",
    page=34,
    note="first form without the absolute value (signed), with the generated root diameter d_fE",
)
def tooth_depth(d_a_mm: float, d_fE_mm: float) -> float:
    """Tooth depth: h = (d_a - d_fE) / 2."""
    d_a = positive_input(d_a_mm, "tip diameter d_a")
    d_fE = positive_input(d_fE_mm, "generated root diameter d_fE")
    if d_fE >= d_a:
        raise GeometryInfeasibleError(
            f"root diameter {d_fE!r} does not lie below the tip diameter {d_a!r}"
        )
    return 0.5 * (d_a - d_fE)


@eq(SOURCE, "(36)", section="4.6.2", page=34, note="first form without the absolute value (signed)")
def addendum(d_a_mm: float, d_mm: float) -> float:
    """Addendum: h_a = (d_a - d) / 2 (signed; negative for a tip circle below the reference circle)."""
    return 0.5 * (
        positive_input(d_a_mm, "tip diameter d_a") - positive_input(d_mm, "reference diameter d")
    )


@eq(
    SOURCE,
    "(37)",
    section="4.6.2",
    page=34,
    note="first form without the absolute value (signed), with the generated root diameter d_fE",
)
def dedendum(d_mm: float, d_fE_mm: float) -> float:
    """Dedendum: h_f = (d - d_fE) / 2 (signed; negative for a root circle above the reference
    circle, which Eq. (37) admits with its absolute value: x_E m_n > h_aP0)."""
    d = positive_input(d_mm, "reference diameter d")
    d_fE = positive_input(d_fE_mm, "generated root diameter d_fE")
    return 0.5 * (d - d_fE)


@eq(
    SOURCE,
    "(38)",
    section="4.7.1",
    page=35,
    note="on the tip cylinder (index a), with the generated half angle",
)
@eq(SOURCE, "(40)", section="4.7.2", page=35)
@eq(SOURCE, "(12)", section="4.3.5", page=29)
def tip_tooth_thickness(d_a_mm: float, d_b_mm: float, psi_rad: float, alpha_t_rad: float) -> float:
    """Transverse tooth thickness on the tip circle: s_at = d_a psi_a with
    psi_a = psi + inv(alpha_t) - inv(alpha_at), cos(alpha_at) = d_b / d_a (§7.9: Eq. (38)).

    ``psi_rad`` is the tooth thickness half angle at the reference circle with x_E (§4.7). A tip
    circle beyond the pointed tooth raises ``GeometryInfeasibleError`` (Eq. (40)).
    """
    d_a = positive_input(d_a_mm, "tip diameter d_a")
    alpha_at = iv.transverse_profile_angle_at(d_a, d_b_mm)
    psi_a = iv.tooth_thickness_half_angle_at(psi_rad, alpha_t_rad, alpha_at)
    return iv.transverse_tooth_thickness_at(d_a, psi_a)


@eq(SOURCE, "(48)", section="4.7.5", page=37, note="on the tip cylinder (index a)")
@eq(SOURCE, "(8)", section="4.3.3", page=28)
def normal_tip_tooth_thickness(
    s_at_mm: float, d_a_mm: float, d_mm: float, beta_rad: float
) -> float:
    """Normal tooth thickness on the tip cylinder: s_an = s_at cos(beta_a), tan(beta_a) = tan(beta) d_a / d."""
    beta_a = iv.helix_angle_at(d_a_mm, d_mm, beta_rad)
    return iv.normal_tooth_thickness_at(s_at_mm, beta_a)


# --- orchestrator ---------------------------------------------------------------------------------


def _warning(code: str, field: str, message: str) -> InputWarning:
    return InputWarning(code=code, field=field, message=message)


def _supported_tool(role: str, gear: GearInput, pair: PairInput) -> ToolProfile:
    tool = gear.tool
    if tool.kind is not ToolKind.RACK:
        raise NotSupportedError(
            f"{role}: tools of kind {tool.kind.value!r} are a prepared extension point"
        )
    if tool.protuberance_mm > 0.0 or tool.protuberance_angle_deg is not None:
        raise NotSupportedError(
            f"{role}: a tool with a protuberance flank is a prepared extension point (DIN 3960 A.3.3)"
        )
    if tool.machining_allowance_mm > 0.0:
        raise NotSupportedError(
            f"{role}: the tool leaves a machining allowance q = {tool.machining_allowance_mm!r} mm; "
            "the finishing tool that removes it is a prepared extension point (DIN ISO 21771 §7.2, "
            "Bild 36 b)); the generation of a finished gear needs q = 0"
        )
    # "same as the gear" within the tolerance of the contract (models.inputs, 1e-6 relative):
    # the generation then uses the module and the pressure angle of the gear
    if tool.normal_module_mm is not None and not math.isclose(
        tool.normal_module_mm, pair.normal_module_mm, rel_tol=SAME_TOOL_TOLERANCE
    ):
        raise NotSupportedError(
            f"{role}: a tool module m_n0 = {tool.normal_module_mm!r} that differs from the gear "
            f"module {pair.normal_module_mm!r} is a prepared extension point (generating gear with "
            "alpha_wt0, DIN ISO 21771 §7.6 Bild 39 note)"
        )
    if tool.profile_angle_deg is not None and not math.isclose(
        tool.profile_angle_deg, pair.normal_pressure_angle_deg, rel_tol=SAME_TOOL_TOLERANCE
    ):
        raise NotSupportedError(
            f"{role}: a tool profile angle alpha_P0 = {tool.profile_angle_deg!r} deg that differs from "
            f"the pressure angle {pair.normal_pressure_angle_deg!r} deg is a prepared extension point"
        )
    if tool.edge_break_angle_deg is not None and tool.root_form_height_factor is None:
        raise InputRangeError(
            f"{role}: the edge break flank of the tool needs the height h_FfP0 at which it starts "
            "(root_form_height_factor)"
        )
    if (
        tool.dedendum_factor is not None
        and tool.root_form_height_factor is not None
        and tool.dedendum_factor < tool.root_form_height_factor
    ):
        raise InputRangeError(
            f"{role}: the tool dedendum h_fP0* = {tool.dedendum_factor!r} must not lie below the "
            f"root form height h_FfP0* = {tool.root_form_height_factor!r} (STplus raises it to that "
            "value)"
        )
    if (
        has_edge_break_flank(tool)
        and tool.edge_break_angle_deg is not None
        and tool.edge_break_angle_deg > MAX_EDGE_BREAK_ANGLE_DEG
    ):
        raise InputRangeError(
            f"{role}: an edge break flank of {tool.edge_break_angle_deg!r} deg is steeper than "
            f"{MAX_EDGE_BREAK_ANGLE_DEG!r} deg: the chamfer it generates is not resolved "
            "numerically (DIN 3960 (A.3.05)); a tool without edge break flank has its dedendum "
            "on its root form height"
        )
    if has_edge_break_flank(tool) and gear.tip_chamfer_radial_mm > 0.0:
        raise NotSupportedError(
            f"{role}: a tip chamfer given as an input together with an edge break flank of the tool "
            "is not supported; give one of the two"
        )
    return tool


MAX_EDGE_BREAK_ANGLE_DEG = 89.9
"""Steepest edge break flank the generation computes. DIN 3960 (A.3.05) forms the residual tip
thickness as the difference of two involute functions of angles next to 90 degrees, whose error
grows with 1 / cos^2: 0,15 nm at 89,99 degrees, 15 nm at 89,999 degrees, no digit left at
89,9999 degrees (gate report increment 3, G3Y-02). A tool without edge break flank has its
dedendum on its root form height instead of such an angle."""


def _involute_diameter_at_height(
    r_mm: float, d_b_mm: float, alpha_t_rad: float, height_mm: float
) -> float:
    """Diameter of the involute point generated by a straight flank point ``height_mm`` above
    the pitch line: the point of the line of action at height / sin(alpha_t) beyond C."""
    reach = r_mm * math.sin(alpha_t_rad) + height_mm / math.sin(alpha_t_rad)
    return 2.0 * math.hypot(0.5 * d_b_mm, reach)


def _gear_generation(role: str, gear: GearInput, pair: PairInput, x: float) -> GearGeneration:
    tool = _supported_tool(role, gear, pair)
    z = gear.number_of_teeth
    m_n = pair.normal_module_mm
    alpha_n = math.radians(pair.normal_pressure_angle_deg)
    beta = math.radians(pair.helix_angle_deg if role == "pinion" else -pair.helix_angle_deg)
    warnings: list[InputWarning] = []

    # generating profile shift: Eq. (123), (124)
    allowance = gear.tooth_thickness_allowance_um
    if allowance is None:
        x_Es = x_Ei = generating_profile_shift_coefficient(x, m_n, alpha_n, 0.0)
        warnings.append(
            _warning(
                "no_tooth_thickness_allowance",
                "tooth_thickness_allowance_um",
                f"{role}: no tooth thickness allowance given; the gear is generated with the "
                "nominal tooth thickness, x_E = x (Eq. (123) with E_sns = 0)",
            )
        )
    else:
        x_Es = generating_profile_shift_coefficient(x, m_n, alpha_n, allowance[0])
        x_Ei = generating_profile_shift_coefficient(x, m_n, alpha_n, allowance[1])
    x_E = x_Es

    # the tool in absolute values
    h_aP0 = tool.addendum_factor * m_n
    rho = tool.tip_radius_factor * m_n
    h_FaP0 = tool_tip_form_height(h_aP0, rho, alpha_n)
    h_FfP0 = None if tool.root_form_height_factor is None else tool.root_form_height_factor * m_n
    h_fP0 = None if tool.dedendum_factor is None else tool.dedendum_factor * m_n

    # reference and base circles, the tooth thickness with x_E (§4.7)
    d = iv.reference_diameter(z, m_n, beta)
    alpha_t = iv.transverse_pressure_angle(alpha_n, beta)
    d_b = iv.base_diameter(z, m_n, alpha_n, beta)
    psi_E = iv.tooth_thickness_half_angle(z, x_E, alpha_n)
    psi_bE = iv.base_tooth_thickness_half_angle(psi_E, alpha_t)

    # the tool must be a tool on every path: the tip rounding checks that its straight flank
    # exists and that its roundings do not overlap (the tool tooth is not pointed)
    rounding = tr.tip_rounding(z, m_n, alpha_n, beta, h_aP0, rho, x_E)

    # root: Eq. (125), (135), (128) or the intersection of fillet and involute
    d_fE = generated_root_diameter(d, x_E, m_n, h_aP0)
    d_fEi = generated_root_diameter(d, x_Ei, m_n, h_aP0)
    x_Emin = min_generating_profile_shift_coefficient(h_FaP0, m_n, z, alpha_t, beta)
    undercut = x_E < x_Emin
    if undercut:
        d_Ff, _, _ = tr.root_form_diameter_by_intersection(
            rounding, d_b, psi_bE, undercut_expected=True
        )
        warnings.append(
            _warning(
                "root_form_diameter_by_intersection",
                "root_form_diameter_mm",
                f"{role}: undercut, x_E = {x_E!r} < x_Emin = {x_Emin!r} (Eq. (135)); the root form "
                "diameter is the intersection of the fillet with the involute (§7.6), Eq. (128) "
                "does not apply",
            )
        )
    else:
        d_Ff = root_form_diameter(d, alpha_t, h_FaP0, x_E, m_n, d_b)

    # tip
    d_a = gear.tip_diameter_mm
    if d_a is None:
        raise InputRangeError(
            f"{role}: the generation needs the tip diameter; give tip_diameter_mm or apply "
            "with_nominal_tip_diameters (Eq. (33)) explicitly"
        )
    cut = False
    if h_fP0 is not None:
        topping = d + 2.0 * (x_E * m_n + h_fP0)
        if topping < d_a * (1.0 - EPS):
            # the root line of the tool lies on the circle of the diameter d + 2 (x_E m_n + h_fP0)
            # while the gear is generated (Eq. (125) with the root line in place of the tip
            # line); what lies beyond it is cut away (user decision 2026-10-03, ADR-114: as
            # STplus, "Kopfkreis ... von Wkz mit Fusshoehenfaktor geschnitten")
            warnings.append(
                _warning(
                    "tip_circle_cut_by_tool",
                    "tip_diameter_mm",
                    f"{role}: the root line of the tool (h_fP0 = {h_fP0!r} mm) lies below the given "
                    f"tip circle d_a = {d_a!r} mm; the tool cuts the tip circle to d_a = "
                    f"{topping!r} mm = d + 2 (x_E m_n + h_fP0)"
                    + (
                        "; the given tip chamfer is applied at the cut tip circle"
                        if gear.tip_chamfer_radial_mm > 0.0
                        else ""
                    ),
                )
            )
            d_a, cut = topping, True
    h_K = gear.tip_chamfer_radial_mm
    s_aK: float | None = None
    if has_edge_break_flank(tool):
        assert h_FfP0 is not None and tool.edge_break_angle_deg is not None
        alpha_tK = edge_break_transverse_angle(math.radians(tool.edge_break_angle_deg), beta)
        d_bK = edge_break_base_diameter(d, alpha_tK)
        s_tK = edge_break_transverse_tooth_thickness(m_n, beta, h_FfP0, alpha_t, alpha_tK, x_E)
        psi_bK = edge_break_base_half_angle(s_tK, d, alpha_tK)
        d_Fa = tip_form_diameter_from_edge_break(d_b, d_bK, psi_bE, psi_bK, d_a)
        h_K = tip_chamfer_height(d_a, d_Fa)
        if d_Fa < d_a:
            # (a tooth the flanks make pointed below the tip circle raises in this function)
            s_aK = residual_tip_thickness(d_a, d_bK, psi_bK)
        else:
            warnings.append(
                _warning(
                    "edge_break_flank_not_reaching_the_tip",
                    "tip_form_diameter_mm",
                    f"{role}: the edge break flank of the tool does not reach the tip circle: "
                    "no chamfer, d_Fa = d_a",
                )
            )
    else:
        if tool.edge_break_angle_deg is not None:
            warnings.append(
                _warning(
                    "edge_break_angle_without_flank",
                    "tool_edge_break_angle_deg",
                    f"{role}: the tool gives an edge break angle, but its dedendum equals the "
                    "root form height: there is no edge break flank and no chamfer by the tool",
                )
            )
        elif h_FfP0 is not None and (h_fP0 is None or h_fP0 > h_FfP0 * (1.0 + EPS)):
            reach = _involute_diameter_at_height(0.5 * d, d_b, alpha_t, x_E * m_n + h_FfP0)
            if reach < d_a * (1.0 - EPS):
                raise NotSupportedError(
                    f"{role}: the tool root form height h_FfP0 = {h_FfP0!r} mm is given without an "
                    "edge break angle, and the straight flank ends below the tip circle (the "
                    f"involute it generates ends at {reach!r} mm); the tool root rounding above "
                    "h_FfP0 (DIN 3960 Bild A.1, rho_fP0) that would generate the tip is a prepared "
                    "extension point"
                )
            warnings.append(
                _warning(
                    "edge_break_angle_not_given",
                    "tool_edge_break_angle_deg",
                    f"{role}: the tool gives a root form height h_FfP0 without an edge break angle; "
                    "the straight flank reaches the tip circle, so no edge break is generated",
                )
            )
        d_Fa = pr.tip_form_diameter(d_a, h_K)
        if h_K > 0.0:
            if gear.residual_tip_thickness_mm is None:
                warnings.append(
                    _warning(
                        "tip_chamfer_shape_not_given",
                        "residual_tip_thickness_mm",
                        f"{role}: the tip chamfer is given by its radial height h_K = {h_K!r} mm "
                        "only; its residual tooth thickness s_aK (DIN ISO 21771 §6.1.2, Bild 24) "
                        "is not given",
                    )
                )
            else:
                s_aK = gear.residual_tip_thickness_mm
    if d_Ff >= d_Fa * (1.0 - EPS):
        raise GeometryInfeasibleError(
            f"{role}: root form diameter d_Ff = {d_Ff!r} does not lie below the tip form diameter "
            f"d_Fa = {d_Fa!r}: the gear has no involute"
            + (f" (the tool cuts the tip circle to {d_a!r} mm)" if cut else "")
        )
    s_at = tip_tooth_thickness(d_a, d_b, psi_E, alpha_t)
    if s_at <= 0.0:
        raise GeometryInfeasibleError(
            f"{role}: the tooth is pointed at the tip circle d_a = {d_a!r} mm (Eq. (40): the flanks "
            "meet there); give a smaller tip diameter"
        )
    if s_aK is not None and s_aK > s_at * (1.0 + EPS):
        raise InputRangeError(
            f"{role}: residual tip thickness s_aK = {s_aK!r} exceeds the tip tooth thickness "
            f"s_at = {s_at!r}"
        )
    return GearGeneration(
        number_of_teeth=z,
        profile_shift_coefficient=x,
        tool_profile_angle_deg=pair.normal_pressure_angle_deg,
        tool_addendum_mm=h_aP0,
        tool_tip_radius_mm=rho,
        tool_tip_form_height_mm=h_FaP0,
        tool_root_form_height_mm=h_FfP0,
        # (the angle of the flank the tool has; an angle without a flank is not passed on)
        tool_edge_break_angle_deg=(
            tool.edge_break_angle_deg if has_edge_break_flank(tool) else None
        ),
        machining_allowance_mm=tool.machining_allowance_mm,
        upper_generating_profile_shift_coefficient=x_Es,
        lower_generating_profile_shift_coefficient=x_Ei,
        generating_profile_shift_coefficient=x_E,
        min_generating_profile_shift_coefficient=x_Emin,
        undercut=undercut,
        generated_root_diameter_mm=d_fE,
        lower_generated_root_diameter_mm=d_fEi,
        root_form_diameter_mm=d_Ff,
        tip_diameter_mm=d_a,
        tip_form_diameter_mm=d_Fa,
        tip_chamfer_radial_mm=h_K,
        residual_tip_thickness_mm=s_aK,
        transverse_tip_tooth_thickness_mm=s_at,
        normal_tip_tooth_thickness_mm=normal_tip_tooth_thickness(s_at, d_a, d, beta),
        tooth_depth_mm=tooth_depth(d_a, d_fE),
        addendum_mm=addendum(d_a, d),
        dedendum_mm=dedendum(d, d_fE),
        warnings=tuple(warnings),
    )


def compute_generation(pair: PairInput) -> GenerationResult:
    """Tool-based generation of both gears and the pair geometry that follows (DIN ISO 21771 §7).

    The profile shift coefficients are resolved by the rule of ADR-107. Each gear is generated by
    its own rack-type tool at the upper tooth thickness allowance; the pair geometry is then
    computed with the generated root form and tip form diameters, which gives the tip clearance
    (Eq. (60)) and the form over-dimension (Eq. (76)) per gear. Not supported (typed errors):
    tools with a protuberance or a machining allowance, tools with a module or profile angle that
    differs from the gear's, shaper and form tools, internal gears.

    A tip circle that lies above the root line of its tool is cut to d + 2 (x_E m_n + h_fP0)
    with the warning ``tip_circle_cut_by_tool`` (user decision 2026-10-03, ADR-114); the
    generated tip diameter is ``gears.<role>.tip_diameter_mm`` and the pair geometry is computed
    with it, while ``inputs`` keeps the pair as given.
    """
    pair = pr._checked(pair)
    x_1, x_2, _, _ = pr._resolve(pair)
    gears: Pair[GearGeneration] = Pair(
        pinion=_gear_generation("pinion", pair.gears.pinion, pair, x_1),
        wheel=_gear_generation("wheel", pair.gears.wheel, pair, x_2),
    )
    # the pair meshes with the tip circles the tools leave (a tool cuts a tip circle that lies
    # above its root line); ``inputs`` of the result stays the pair as given
    generated_pair = pair.model_copy(
        update={
            "gears": Pair(
                pinion=pair.gears.pinion.model_copy(
                    update={"tip_diameter_mm": gears.pinion.tip_diameter_mm}
                ),
                wheel=pair.gears.wheel.model_copy(
                    update={"tip_diameter_mm": gears.wheel.tip_diameter_mm}
                ),
            )
        }
    )
    geometry = pr.compute_pair_geometry(
        generated_pair,
        root_form_diameter_mm=Pair(
            pinion=gears.pinion.root_form_diameter_mm, wheel=gears.wheel.root_form_diameter_mm
        ),
        tip_form_diameter_mm=Pair(
            pinion=gears.pinion.tip_form_diameter_mm, wheel=gears.wheel.tip_form_diameter_mm
        ),
    )
    a_w = geometry.centre_distance_mm
    clearance: Pair[float] = Pair(
        pinion=pr.tip_clearance(
            a_w, gears.pinion.tip_diameter_mm, gears.wheel.generated_root_diameter_mm
        ),
        wheel=pr.tip_clearance(
            a_w, gears.wheel.tip_diameter_mm, gears.pinion.generated_root_diameter_mm
        ),
    )
    over_dimension: Pair[float] = Pair(
        pinion=pr.form_over_dimension(
            geometry.sap_diameter_mm.pinion, gears.pinion.root_form_diameter_mm
        ),
        wheel=pr.form_over_dimension(
            geometry.sap_diameter_mm.wheel, gears.wheel.root_form_diameter_mm
        ),
    )
    warnings = [*gears.pinion.warnings, *gears.wheel.warnings]
    for role, value in zip(ROLES, clearance.as_tuple(), strict=True):
        if value <= 0.0:
            warnings.append(
                _warning(
                    "tip_clearance_not_positive",
                    "tip_clearance_mm",
                    f"{role}: the tip clearance c = {value!r} mm is not positive: the tip cuts into "
                    "the root of the mating gear",
                )
            )
    kept = {
        "tip_chamfer_input_not_used",
        "tip_form_diameter_not_generated",
        "root_form_diameter_not_checked",
    }
    warnings += [w for w in geometry.warnings if w.code not in kept]
    return GenerationResult(
        inputs=pair,
        gears=gears,
        pair_geometry=geometry,
        tip_clearance_mm=clearance,
        form_over_dimension_mm=over_dimension,
        warnings=tuple(warnings),
    )
