"""Fillet generated by the tip rounding of a rack-type tool, in the transverse section.

Sources. The law of gearing: the common normal of two mating profiles passes through the pitch
point (Linke 2010 §1.3, p. 41; FVA 604 I §3.1 Eq. (3.2) and (3.3), p. 12 and 13: for cylindrical
gears the flank normal at the point of contact always passes through the pitch point). The
fillet of a spur gear is the parallel curve at the distance rho_aP0 of the trochoid that the
centre of the tool tip rounding describes while the rack rolls on the reference circle (FVA 604 I
p. 28 with Abbildung 4.6; Linke 2010 §2.3.2, Bild 2.3/1 p. 111, Eq. (2.3/11) and (2.3/12) p. 112).
For a helical gear the tool profile is stretched by 1 / cos(beta) along the rack in the transverse
section, the heights stay, and the tip rounding becomes an ellipse (FVA 604 I p. 29). FVA 604 I
approximates the ellipse by a circle of radius rho_aP0 / cos(beta); this module uses the ellipse.

Formulation. Every point of the tool profile is taken together with its tangent. It generates a
point of the gear in the rolling position in which its normal passes through the pitch point
(the envelope of the family of tool positions). Applied to the straight flank this gives the
involute (the test of this module), applied to the tip line the root circle, applied to the tip
rounding the fillet. No closed formula of the fillet is transcribed from a source: the envelope
condition is applied to the ellipse directly. Where the fillet cuts into the involute (undercut,
DIN ISO 21771:2014-08 §7.6, p. 70; DIN 3960:1987-03 §3.6.7, p. 16) the root form circle is the
intersection of the two curves, found numerically.

Frames. Rack frame: xi along the rack, eta radial, positive away from the gear centre, the
pitch line at eta = 0, the tool tooth centred at xi = 0 (it generates a space of the gear); the
datum line lies at eta = x_E m_n. Gear frame: the gear centre at the origin, the space generated
by the tool tooth centre on the +Y axis, the adjacent tooth centred at the angle pi / z towards
+X. A generated point is returned as (radius, psi), psi being its angle from the centre of that
tooth, i.e. the tooth thickness half angle of DIN ISO 21771 §4.7 at that radius. The right flank
of the tool tooth (xi > 0) is used; the tooth is symmetric (flank symmetry is data-driven only
where the inputs of the two flanks differ, which the contracts do not admit).

Tolerance. A generated radius within ``EPS`` (relative) of the base circle counts as on it.
"""

import math
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray
from scipy.optimize import brentq

from gearcore import involute as iv
from gearcore._guards import HALF_PI, helix, pressure_angle, teeth
from gearcore._safe import EPS, finite_input, finite_result, integer_input, positive_input
from gearcore.errors import GeometryInfeasibleError, InputRangeError, SolverError
from gearcore.trace import eq

LINKE = "Linke2010"
FVA = "FVA604-I:2012"
SOURCE = "ISO21771:2014"
OLD = "DIN3960:1987"

SAMPLES = 4001
"""Points of the parameter grid of the fillet used to bracket the cusp and the intersection."""

GAP_TOLERANCE = 1.0e-13
"""Half angle (rad) by which the fillet must lie inside the involute to count as cutting into it.
The gap is a difference of angles of order 0,1 rad computed from coordinates, so its rounding
noise is of order 1e-16 rad; 1e-13 rad is 1e-11 mm on a radius of 100 mm. Just below the
undercut limit the cut is shallower than that: see ``root_form_diameter_by_intersection``."""

END_TOLERANCE = 1.0e-9
"""Half angle (rad) within which the end of a fillet free of undercut lies on the involute (it is
tangent there; the parameter grid resolves the end to 1e-9 mm)."""

EQ_EXEMPT = ("fillet_curve",)
"""Samples the traced ``fillet_point``; carries no equation of its own."""

Array = NDArray[np.float64]


@dataclass(frozen=True, slots=True)
class TipRounding:
    """The tip rounding of a rack-type tool in the transverse section, positioned for rolling.

    An ellipse with the semi-axes ``semi_axis_xi_mm`` (along the rack, rho_aP0 / cos beta) and
    ``semi_axis_eta_mm`` (radial, rho_aP0), tangent to the tip line at the parameter -pi / 2 and
    to the right flank at ``flank_parameter_rad`` = -alpha_n. ``reference_radius_mm`` is r = d / 2
    of the gear, ``space_half_angle_rad`` = pi / z the angle from the space centre to the centre of
    the adjacent tooth.
    """

    reference_radius_mm: float
    centre_xi_mm: float
    centre_eta_mm: float
    semi_axis_xi_mm: float
    semi_axis_eta_mm: float
    axis_ratio: float
    """semi_axis_eta / semi_axis_xi = cos(beta), kept apart so that a sharp corner (both zero)
    rolls like the limit of a rounding."""
    flank_parameter_rad: float
    space_half_angle_rad: float

    @property
    def root_radius_mm(self) -> float:
        """Radius of the root circle: the envelope of the tip line, r + eta_tip."""
        return self.reference_radius_mm + self.centre_eta_mm - self.semi_axis_eta_mm

    @property
    def start_half_angle_rad(self) -> float:
        """psi of the point where the fillet leaves the root circle (parameter -pi / 2)."""
        return self.space_half_angle_rad - self.centre_xi_mm / self.reference_radius_mm

    def point(self, theta_rad: float | Array) -> tuple[float | Array, float | Array]:
        """(xi, eta) of the ellipse at the parameter theta."""
        return (
            self.centre_xi_mm + self.semi_axis_xi_mm * np.cos(theta_rad),
            self.centre_eta_mm + self.semi_axis_eta_mm * np.sin(theta_rad),
        )

    def tangent(self, theta_rad: float | Array) -> tuple[float | Array, float | Array]:
        """d(xi, eta) / d theta of the ellipse at the parameter theta."""
        return (
            -self.semi_axis_xi_mm * np.sin(theta_rad),
            self.semi_axis_eta_mm * np.cos(theta_rad),
        )


def _real(value: float | Array, what: str) -> Array:
    """A caller-supplied number, or array of real numbers, as a finite binary64 array."""
    if isinstance(value, np.ndarray):
        if not (np.issubdtype(value.dtype, np.floating) or np.issubdtype(value.dtype, np.integer)):
            raise InputRangeError(f"{what} array must hold real numbers, got dtype {value.dtype}")
        values = value.astype(np.float64)
        if not np.all(np.isfinite(values)):
            raise InputRangeError(f"{what} must be finite")
        return values
    return np.asarray(finite_input(value, what), dtype=np.float64)


def _same_shape(what: str, *values: Array) -> None:
    """Arrays given together must broadcast (numbers always do)."""
    try:
        np.broadcast_shapes(*(value.shape for value in values))
    except ValueError:
        shapes = [value.shape for value in values]
        raise InputRangeError(f"{what}: the arrays do not have one shape, got {shapes!r}") from None


def _checked_rounding(rounding: TipRounding) -> TipRounding:
    if not isinstance(rounding, TipRounding):
        raise InputRangeError(
            f"a TipRounding of tip_rounding is required, got {type(rounding).__name__}"
        )
    return rounding


# --- the tool in the transverse section ---------------------------------------------------------


@eq(FVA, "Abbildung 4.6", page=28, note="tool reference profile in the transverse section")
@eq(
    FVA,
    "p. 29",
    page=29,
    note="stretched by 1 / cos(beta) along the rack: the tip rounding becomes an ellipse",
)
@eq(LINKE, "Bild 2.3/1", section="2.3.2", page=111, note="position of the tip rounding centre M")
def tip_rounding(
    z: int,
    m_n_mm: float,
    alpha_n_rad: float,
    beta_rad: float,
    h_aP0_mm: float,
    rho_aP0_mm: float,
    x_E: float,
) -> TipRounding:
    """The tip rounding of the tool, positioned in the rack frame for rolling on the gear.

    In the normal section the rounding is the circle of radius rho_aP0 that touches the tip line
    and the flank: its centre lies rho_aP0 above the tip line and, across the tooth, at
    p_n / 4 - (h_aP0 - rho_aP0) tan(alpha_n) - rho_aP0 / cos(alpha_n) from the tooth centre. In the
    transverse section the abscissa is divided by cos(beta) and the circle is the ellipse with
    the semi-axes rho_aP0 / cos(beta) and rho_aP0. rho_aP0 = 0 is the sharp corner of the tool
    (a degenerate ellipse; the fillet is then the trochoid of the corner).

    Two conditions make the tool a tool, and they are the same on every path of the generation:
    the straight flank must exist, h_aP0 > rho_aP0 (1 - sin alpha_n) (the bracket of Eq. (128) NB
    at x_E = 0, ``generation.tool_tip_form_height``), and the tip roundings of the two flanks must
    not overlap, which also rejects a tool addendum so tall that the tool tooth is pointed:
    ``GeometryInfeasibleError``.
    """
    number = teeth(z)
    m_n = positive_input(m_n_mm, "normal module m_n")
    alpha_n = pressure_angle(alpha_n_rad, "normal pressure angle alpha_n")
    beta = helix(beta_rad)
    h_aP0 = positive_input(h_aP0_mm, "tool addendum h_aP0")
    rho = finite_input(rho_aP0_mm, "tool tip radius rho_aP0")
    if rho < 0.0:
        raise InputRangeError(f"tool tip radius rho_aP0 must be >= 0, got {rho_aP0_mm!r}")
    if h_aP0 - rho * (1.0 - math.sin(alpha_n)) <= 0.0:
        raise GeometryInfeasibleError(
            f"tool tip radius rho_aP0 = {rho!r} leaves no straight flank on the tool addendum "
            f"h_aP0 = {h_aP0!r}"
        )
    shift = finite_input(x_E, "generating profile shift coefficient x_E")
    centre_u = math.pi * m_n / 4.0 - (h_aP0 - rho) * math.tan(alpha_n) - rho / math.cos(alpha_n)
    if centre_u < -EPS * m_n:
        raise GeometryInfeasibleError(
            f"tool addendum h_aP0 = {h_aP0!r} with tip radius rho_aP0 = {rho!r}: the tool tooth is "
            f"pointed or the tip roundings of both flanks overlap (the rounding centre lies "
            f"{-centre_u!r} mm beyond the tooth centre; the tool tooth of module {m_n!r} is pointed "
            f"{math.pi * m_n / (4.0 * math.tan(alpha_n))!r} mm above the datum line)"
        )
    d = iv.reference_diameter(number, m_n, beta)
    return TipRounding(
        reference_radius_mm=0.5 * d,
        centre_xi_mm=finite_result(max(centre_u, 0.0) / math.cos(beta), "xi_c"),
        centre_eta_mm=shift * m_n - h_aP0 + rho,
        semi_axis_xi_mm=rho / math.cos(beta),
        semi_axis_eta_mm=rho,
        axis_ratio=math.cos(beta),
        flank_parameter_rad=-alpha_n,
        space_half_angle_rad=math.pi / number,
    )


# --- rolling ------------------------------------------------------------------------------------


@eq(
    LINKE,
    "Verzahnungsgesetz",
    section="1.3",
    page=41,
    note="the common normal passes through the pitch point C",
)
@eq(
    FVA,
    "(3.2)",
    section="3.1",
    page=12,
    note="the relative velocity of the contact points is tangential",
)
@eq(
    FVA,
    "(3.3)",
    section="3.1",
    page=13,
    note="for cylindrical gears the flank normal at the contact point passes through the pitch point",
)
def pitch_point_position(
    xi_mm: float | Array,
    eta_mm: float | Array,
    tangent_xi: float | Array,
    tangent_eta: float | Array,
) -> float | Array:
    """Position c of the pitch point on the pitch line at which the rack profile point (xi, eta)
    with the tangent direction (tangent_xi, tangent_eta) generates: the normal of the profile at
    that point passes through (c, 0), i.e. (xi - c) tangent_xi + eta tangent_eta = 0.

    A tangent parallel to the radial direction (tangent_xi = 0) has its normal parallel to the
    pitch line; such a point generates nowhere (``SolverError``).
    """
    xi, eta = _real(xi_mm, "profile point xi"), _real(eta_mm, "profile point eta")
    t_xi, t_eta = _real(tangent_xi, "tangent xi"), _real(tangent_eta, "tangent eta")
    _same_shape("pitch point position", xi, eta, t_xi, t_eta)
    if np.any(np.abs(t_xi) <= EPS * np.hypot(t_xi, t_eta)):
        raise SolverError("a profile point whose tangent is radial generates no point of the gear")
    result = xi + eta * t_eta / t_xi
    if np.ndim(result) == 0:
        return finite_result(float(result), "pitch point position c")
    return np.asarray(result)


@eq(
    LINKE,
    "Bild 1/24",
    section="1.3",
    page=42,
    note="the gear turns by the arc c / r while the rack moves by c; the contact point is fixed to the gear",
)
@eq(
    FVA,
    "Abbildung 4.7",
    page=30,
    note="rolling of the rack pitch line on the reference circle (generating pitch circle)",
)
def generated_point(
    xi_mm: float | Array,
    eta_mm: float | Array,
    c_mm: float | Array,
    r_mm: float,
) -> tuple[float | Array, float | Array]:
    """The rack point (xi, eta) in the gear frame when the pitch point is at c on the rack.

    Rolling without slip: the rack point lies at (xi - c, r + eta) relative to the gear centre
    while the gear has turned by c / r. Returned as (radius, angle from the +Y axis towards +X).
    """
    r = positive_input(r_mm, "reference radius r")
    xi, eta = _real(xi_mm, "profile point xi"), _real(eta_mm, "profile point eta")
    c = _real(c_mm, "pitch point position c")
    _same_shape("generated point", xi, eta, c)
    phi = c / r
    x = xi - c
    y = r + eta
    gear_x = x * np.cos(phi) + y * np.sin(phi)
    gear_y = -x * np.sin(phi) + y * np.cos(phi)
    radius = np.hypot(gear_x, gear_y)
    angle = np.arctan2(gear_x, gear_y)
    if np.ndim(radius) == 0:
        return finite_result(float(radius), "generated radius"), float(angle)
    return np.asarray(radius), np.asarray(angle)


# --- the fillet ---------------------------------------------------------------------------------


@eq(
    FVA,
    "p. 28",
    page=28,
    note="fillet = envelope of the tool tip rounding; spur gear: parallel curve of the trochoid of its centre",
)
@eq(
    LINKE,
    "(2.3/11)",
    section="2.3.2",
    page=112,
    note="coordinates of the fillet point for a circular tip rounding (spur gear)",
)
@eq(LINKE, "(2.3/12)", section="2.3.2", page=112)
def fillet_point(
    rounding: TipRounding, theta_rad: float | Array
) -> tuple[float | Array, float | Array]:
    """(radius, psi) of the fillet point generated by the ellipse point at the parameter theta.

    psi is the angle from the centre of the adjacent tooth (its tooth thickness half angle at
    that radius). Parameters run from -pi / 2 (tangent to the tip line, the point on the root
    circle) to ``rounding.flank_parameter_rad`` (tangent to the flank, the point where the fillet
    meets the involute for a gear free of undercut).

    The pitch point position of ``pitch_point_position`` is evaluated in closed form for the
    ellipse: the slope of its tangent, eta' / xi' = -cos(beta) cot(theta), does not depend on the
    radius of the rounding, so a sharp corner (rho_aP0 = 0) is the limit of the same formula.
    """
    theta = _parameter(theta_rad, _checked_rounding(rounding))
    xi, eta = rounding.point(theta)
    # (xi - c) xi' + eta eta' = 0 with xi' = -a sin(theta), eta' = b cos(theta), b / a = cos(beta)
    c = xi - eta * rounding.axis_ratio / np.tan(theta)
    radius, angle = generated_point(xi, eta, c, rounding.reference_radius_mm)
    psi = rounding.space_half_angle_rad - angle
    if np.ndim(radius) == 0:
        return float(radius), float(psi)
    return np.asarray(radius), np.asarray(psi)


def _parameter(theta_rad: float | Array, rounding: TipRounding) -> Array:
    """The fillet parameter(s) as a float array within [-pi/2, flank parameter] (``EPS`` slack)."""
    theta = _real(theta_rad, "fillet parameter theta")
    if np.any(theta < -HALF_PI - EPS) or np.any(theta > rounding.flank_parameter_rad + EPS):
        raise InputRangeError(
            f"fillet parameter must lie in [-pi/2, {rounding.flank_parameter_rad!r}], got {theta_rad!r}"
        )
    return theta


def fillet_curve(
    rounding: TipRounding, theta_end_rad: float | None = None, n: int = SAMPLES
) -> tuple[Array, Array, Array]:
    """(theta, radius, psi) of ``n`` fillet points from the root circle to ``theta_end_rad``
    (default: the tangent point with the flank)."""
    end = (
        _checked_rounding(rounding).flank_parameter_rad
        if theta_end_rad is None
        else finite_input(theta_end_rad, "fillet end parameter")
    )
    count = integer_input(n, "number of fillet points")
    if count < 3:
        raise InputRangeError(f"number of fillet points must be >= 3, got {n!r}")
    theta = np.linspace(-HALF_PI, end, count)
    radius, psi = fillet_point(rounding, theta)  # checks the range of the end
    return theta, np.asarray(radius), np.asarray(psi)


@eq(
    SOURCE,
    "(40)",
    section="4.7.2",
    page=35,
    note="psi_y = psi_b - inv(alpha_yt) with the base half angle of Eq. (42)",
)
@eq(SOURCE, "(12)", section="4.3.5", page=29)
def involute_half_angle(radius_mm: float, d_b_mm: float, psi_b_rad: float) -> float:
    """Tooth thickness half angle of the involute at the radius: psi_b - inv(acos(d_b / d)).

    Below the base circle there is no involute: ``GeometryInfeasibleError`` (raised by Eq. (12)).
    """
    d_b = positive_input(d_b_mm, "base diameter d_b")
    alpha = iv.transverse_profile_angle_at(2.0 * positive_input(radius_mm, "radius"), d_b)
    return finite_input(psi_b_rad, "base tooth thickness half angle psi_b") - iv.inv(alpha)


def _ascending_end(radius: Array) -> int:
    """Index of the last point of the ascending branch of the fillet (the cusp, or the end)."""
    steps = np.diff(radius)
    falling = np.flatnonzero(steps <= 0.0)
    return int(falling[0]) if falling.size else int(radius.size) - 1


@eq(
    SOURCE,
    "7.6",
    section="7.6",
    page=70,
    note="with undercut the root form circle is the intersection of the involute with the fillet curve",
)
@eq(
    OLD,
    "3.6.7",
    section="3.6.7",
    page=16,
    note="with undercut the root form circle is the intersection of involute and fillet curve (iteration)",
)
def root_form_diameter_by_intersection(
    rounding: TipRounding, d_b_mm: float, psi_b_rad: float, *, undercut_expected: bool = False
) -> tuple[float, float, bool]:
    """(d_Ff, theta, undercut) of the fillet of a gear.

    The fillet is followed from the root circle outwards (its ascending branch: up to a cusp
    where it turns back, if it has one). Where the fillet lies inside the involute (thinner
    tooth) by more than ``GAP_TOLERANCE`` and then crosses it, the crossing is the root form
    circle (``undercut`` = True) and ``theta`` its parameter; beyond the crossing the fillet lies
    in the space and ends on the mirrored branch of the involute beyond the tangent point T (that
    is the value Eq. (128) would print). Where the fillet never lies inside the involute it ends
    tangentially on the involute at the parameter of the flank tangent point (``undercut`` =
    False); the caller then has the closed form of Eq. (128).

    ``undercut_expected`` says that the caller knows x_E < x_Emin (Eq. (135)). Just below that
    limit the cut into the involute is shallower than ``GAP_TOLERANCE`` (it vanishes like the
    square of the distance to the limit) and no crossing can be resolved; the root form circle
    is then the base circle, where the fillet crosses it (``theta``), and ``undercut`` is True.
    The expectation is checked against the fillet: it must end on the mirrored branch of the
    involute within ``END_TOLERANCE``; a gear free of undercut does so only where its root form
    circle lies within 1e-6 (relative) of the base circle. Else ``SolverError``.
    Without that knowledge a fillet whose end lies off the involute means an inconsistent input
    (psi_b not that of the gear the rounding was built for): ``SolverError``. So does a fillet
    that lies inside the involute without leaving it again.
    """
    d_b = positive_input(d_b_mm, "base diameter d_b")
    psi_b = finite_input(psi_b_rad, "base tooth thickness half angle psi_b")
    if not isinstance(undercut_expected, bool):
        raise InputRangeError(f"undercut_expected must be a bool, got {undercut_expected!r}")
    r_b = 0.5 * d_b
    theta, radius, psi = fillet_curve(rounding)
    end = _ascending_end(radius)
    cusp = end < radius.size - 1
    # the involute exists from the base circle on; a radius within half of EPS below it is on it
    # (Eq. (12) folds that band onto the base circle), which keeps the bracket below valid
    base = r_b * (1.0 - 0.5 * EPS)
    above = radius[: end + 1] >= base
    if not np.any(above):
        if cusp:
            raise SolverError("the fillet turns back below the base circle: no involute to meet")
        raise GeometryInfeasibleError(
            f"the fillet ends below the base circle (radius {float(radius[end])!r} < {r_b!r}): "
            "no involute is generated"
        )

    def gap(t: float) -> float:
        r, p = fillet_point(rounding, t)
        return float(p) - involute_half_angle(float(r), d_b, psi_b)

    first = int(np.flatnonzero(above)[0])
    if first > 0 and radius[first] >= r_b:
        # exact parameter at which the fillet reaches the base circle itself (the band below it
        # only keeps Eq. (12) defined at the root the solver returns)
        theta_base = float(
            brentq(
                lambda t: float(fillet_point(rounding, t)[0]) - r_b,
                theta[first - 1],
                theta[first],
                xtol=1e-15,
                rtol=4.0 * np.finfo(float).eps,
            )
        )
    else:
        # the fillet starts on or above the base circle, or a sample lies within the band
        theta_base = float(theta[first])
    checks = [theta_base, *theta[first : end + 1].tolist()]
    values = [gap(t) for t in checks]
    inside = [i for i, value in enumerate(values) if value < -GAP_TOLERANCE]
    if not inside:
        if cusp:
            raise SolverError(
                "the fillet turns back (cusp) without cutting into the involute: no tooth "
                "profile this module describes"
            )
        if undercut_expected:
            # the fillet of an undercut gear ends on the mirrored branch of the involute beyond
            # T, twice inv(alpha) from the flank; an end anywhere else refutes the caller
            mirrored = 2.0 * (psi_b - involute_half_angle(float(radius[-1]), d_b, psi_b))
            if abs(values[-1] - mirrored) > END_TOLERANCE:
                raise SolverError(
                    f"undercut is expected, but the fillet ends {values[-1]!r} rad from the "
                    f"involute, not on its mirrored branch ({mirrored!r} rad): the gear is not "
                    "undercut, or psi_b does not belong to the gear the rounding was built for"
                )
            # the cut is below the resolution: the involute is usable from the base circle
            return d_b, theta_base, True
        if abs(values[-1]) <= END_TOLERANCE:
            return 2.0 * float(radius[-1]), float(theta[-1]), False
        raise SolverError(
            f"the fillet ends off the involute (gap {values[-1]!r} rad) without cutting into it: "
            "psi_b does not belong to the gear the rounding was built for"
        )
    start = inside[0]
    crossing = next((i for i in range(start, len(values) - 1) if values[i + 1] >= 0.0), None)
    if crossing is None:
        raise SolverError(
            "the fillet lies inside the involute up to its cusp and never leaves it: no tooth "
            "profile this module describes"
        )
    low, high = checks[crossing], checks[crossing + 1]
    theta_star = float(brentq(gap, low, high, xtol=1e-15, rtol=4.0 * np.finfo(float).eps))
    r_star, _ = fillet_point(rounding, theta_star)
    return 2.0 * float(r_star), theta_star, True
