// Parameter glossary (user request 2026-07-04): every symbol used across the workbench with
// its full name, an UNDERSTANDABLE explanation (who influences whom — formulas live in the
// referenced norms), the norms it appears in, and cross-links to related symbols. Rendered by
// the filterable GlossaryPanel. Bilingual, so the panel follows the DE/EN switch.

export type GlossaryCategory =
  | "macro"
  | "tool"
  | "toothform"
  | "micro"
  | "tolerance"
  | "capacity"
  | "fe";

export interface GlossaryEntry {
  symbol: string;
  name: { de: string; en: string };
  unit: string;
  category: GlossaryCategory;
  norms: string[];
  related: string[];
  description: { de: string; en: string };
}

export const CATEGORY_LABELS: Record<GlossaryCategory, { de: string; en: string }> = {
  macro: { de: "Makrogeometrie", en: "Macro geometry" },
  tool: { de: "Werkzeug / Bezugsprofil", en: "Tool / basic rack" },
  toothform: { de: "Zahnform & Fußkurven", en: "Tooth form & root fillets" },
  micro: { de: "Mikrogeometrie", en: "Micro geometry" },
  tolerance: { de: "Toleranzen", en: "Tolerances" },
  capacity: { de: "Tragfähigkeit & Dynamik", en: "Load capacity & dynamics" },
  fe: { de: "FE-Modell & Vernetzung", en: "FE model & meshing" },
};

export const GLOSSARY: GlossaryEntry[] = [
  // ------------------------------------------------------------------ macro geometry
  {
    symbol: "m_n",
    name: { de: "Normalmodul", en: "Normal module" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 780", "ISO 54", "DIN 3960"],
    related: ["z", "d", "m_t", "β"],
    description: {
      de: "Das Grundmaß der Verzahnung: fast alle Abmessungen (Teilkreis, Zahnhöhen, Zahndicke) skalieren mit dem Modul. Größerer Modul = größere, tragfähigere Zähne bei gleicher Radgröße aber kleinerer Zähnezahl.",
      en: "The base size of the gearing: nearly all dimensions (reference diameter, tooth heights, tooth thickness) scale with the module. Larger module = larger, stronger teeth at the same gear size but fewer teeth.",
    },
  },
  {
    symbol: "m_t",
    name: { de: "Stirnmodul", en: "Transverse module" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["m_n", "β"],
    description: {
      de: "Der Modul in der Stirnschnittebene: m_t = m_n/cos β. Bei Geradverzahnung (β = 0°) identisch mit dem Normalmodul; alle Durchmesser rechnen im Stirnschnitt.",
      en: "The module in the transverse plane: m_t = m_n/cos β. Identical to the normal module for spur gears (β = 0°); all diameters are computed in the transverse section.",
    },
  },
  {
    symbol: "z",
    name: { de: "Zähnezahl", en: "Number of teeth" },
    unit: "–",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["m_n", "d", "u", "x"],
    description: {
      de: "Bestimmt zusammen mit dem Modul den Teilkreis (d = z·m_t) und mit der Gegenrad-Zähnezahl die Übersetzung. Kleine Zähnezahlen erhöhen die Unterschnittgefahr (Abhilfe: Profilverschiebung x). kst-E: Ritzel z=51, Rad z=52.",
      en: "Together with the module it sets the reference circle (d = z·m_t) and, with the mating gear, the ratio. Low tooth counts risk undercut (remedy: profile shift x). kst-E: pinion z=51, wheel z=52.",
    },
  },
  {
    symbol: "u",
    name: { de: "Zähnezahlverhältnis", en: "Gear ratio" },
    unit: "–",
    category: "macro",
    norms: ["DIN 3960"],
    related: ["z", "M₂"],
    description: {
      de: "u = z₂/z₁ (Rad zu Ritzel). Bestimmt die Drehzahl- und Momentenübersetzung der Stufe — deshalb wird das Radmoment M₂ im FE-Deck mit z₁/z₂ auf das Ritzel umgerechnet.",
      en: "u = z₂/z₁ (wheel over pinion). Sets the speed and torque conversion of the stage — which is why the wheel torque M₂ is converted with z₁/z₂ to the pinion in the FE deck.",
    },
  },
  {
    symbol: "x",
    name: { de: "Profilverschiebungsfaktor", en: "Profile shift coefficient" },
    unit: "–",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["d_f", "d_a", "s_n", "a_w", "α_wt"],
    description: {
      de: "Radiale Abrückung des Werkzeugs um x·m_n beim Verzahnen. Positives x macht den Zahnfuß dicker (höhere Fußtragfähigkeit, weniger Unterschnitt) und verschiebt d_f/d_a nach außen; die Summe x₁+x₂ legt zusammen mit a den Betriebseingriffswinkel fest.",
      en: "Radial displacement of the tool by x·m_n during generation. Positive x thickens the tooth root (higher root capacity, less undercut) and moves d_f/d_a outward; the sum x₁+x₂ together with a fixes the working pressure angle.",
    },
  },
  {
    symbol: "α_n",
    name: { de: "Normaleingriffswinkel", en: "Normal pressure angle" },
    unit: "°",
    category: "macro",
    norms: ["DIN 867", "ISO 53"],
    related: ["d_b", "α_wt"],
    description: {
      de: "Flankenwinkel des Bezugsprofils (Standard 20°). Bestimmt den Grundkreis der Evolvente und damit die Flankenform: größerer Winkel = dickerer Fuß und höhere Radialkraft, kleinerer = ruhigerer Lauf.",
      en: "Flank angle of the basic rack (standard 20°). Sets the involute base circle and thus the flank shape: larger angle = thicker root and higher radial force, smaller = smoother running.",
    },
  },
  {
    symbol: "β",
    name: { de: "Schrägungswinkel", en: "Helix angle" },
    unit: "°",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["m_t", "ε_β", "b"],
    description: {
      de: "Neigung der Flankenlinie am Teilzylinder; 0° = Geradverzahnung (aktueller Scope). Schrägverzahnung erhöht die Gesamtüberdeckung (leiserer Lauf), erzeugt aber Axialkräfte.",
      en: "Inclination of the tooth trace on the reference cylinder; 0° = spur gearing (current scope). Helical teeth raise the total contact ratio (quieter) but create axial forces.",
    },
  },
  {
    symbol: "a_w",
    name: { de: "Betriebsachsabstand", en: "Working centre distance" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["α_wt", "x", "d_w", "j_n"],
    description: {
      de: "Tatsächlicher Achsabstand im Getriebe. Weicht er vom Null-Achsabstand ab (Profilverschiebungen), ändern sich Betriebseingriffswinkel, Wälzkreise und Flankenspiel. Position der Rot_Nodes im FE-Deck.",
      en: "Actual centre distance in the gearbox. If it differs from the zero-backlash distance (profile shifts), the working pressure angle, pitch circles and backlash change. Position of the FE deck's rotation nodes.",
    },
  },
  {
    symbol: "α_wt",
    name: { de: "Betriebseingriffswinkel", en: "Working transverse pressure angle" },
    unit: "°",
    category: "macro",
    norms: ["DIN 3960"],
    related: ["a_w", "x", "d_w"],
    description: {
      de: "Eingriffswinkel im Betriebswälzpunkt — folgt aus Achsabstand und Summe der Profilverschiebungen (Involuten-Beziehung nach DIN 3960). Bestimmt Kraftrichtung und Wälzkreise.",
      en: "Pressure angle at the working pitch point — follows from centre distance and the sum of profile shifts (involute relation per DIN 3960). Sets the force direction and pitch circles.",
    },
  },
  {
    symbol: "b",
    name: { de: "Zahnbreite", en: "Face width" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 6336-3"],
    related: ["Δz", "ε_β", "n_breite"],
    description: {
      de: "Breite des verzahnten Bereichs; trägt die Last linear. Ritzel und Rad dürfen unterschiedlich breit sein (kst-E: 17/15 mm) — im FE-Modell wälzen sie standardmäßig mittig aufeinander ab, verschiebbar über den Axialversatz Δz.",
      en: "Width of the toothed portion; carries load linearly. Pinion and wheel may differ (kst-E: 17/15 mm) — in the FE model they roll centred on each other by default, adjustable via the axial offset Δz.",
    },
  },
  {
    symbol: "d",
    name: { de: "Teilkreisdurchmesser", en: "Reference diameter" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["m_n", "z", "d_w"],
    description: {
      de: "d = z·m_t — der Bezugskreis, auf dem Modul und Teilung definiert sind. Nicht zu verwechseln mit dem Wälzkreis d_w, der erst durch die Paarung entsteht.",
      en: "d = z·m_t — the reference circle on which module and pitch are defined. Not to be confused with the pitch circle d_w, which only exists in a meshing pair.",
    },
  },
  {
    symbol: "d_b",
    name: { de: "Grundkreisdurchmesser", en: "Base diameter" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["α_n", "d"],
    description: {
      de: "d_b = d·cos α_t — der Kreis, von dem die Evolvente abrollt. Unterhalb des Grundkreises existiert keine Evolvente; dort liegt nur Fußkurve.",
      en: "d_b = d·cos α_t — the circle the involute unrolls from. No involute exists below the base circle; only the root fillet lives there.",
    },
  },
  {
    symbol: "d_a",
    name: { de: "Kopfkreisdurchmesser", en: "Tip diameter" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["d_Na", "x", "c"],
    description: {
      de: "Außendurchmesser des Rads. Wächst mit der Profilverschiebung; die Kopfkante wird per Kopfkantenbruch gebrochen (d_Na = nutzbarer Bereich). Der Kopf des Gegenrads bestimmt den Freigang c in der Fußausrundung.",
      en: "Outside diameter. Grows with profile shift; the tip edge is chamfered (d_Na = usable range). The mating tip governs the root clearance c.",
    },
  },
  {
    symbol: "d_f",
    name: { de: "Fußkreisdurchmesser", en: "Root diameter" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["h_aP0", "x", "ρ_F", "d_Ff"],
    description: {
      de: "Innerster Durchmesser der Zahnlücke — geschnitten vom Werkzeugkopf (h_aP0, x). Zwischen den beiden Fußrundungen einer Lücke bleibt auf d_f ein Fußland-Bogen stehen; die Fußkurve verbindet ihn mit der Flanke.",
      en: "Innermost diameter of the tooth gap — cut by the tool tip (h_aP0, x). A root-land arc remains on d_f between the two fillets of a gap; the fillet connects it to the flank.",
    },
  },
  {
    symbol: "d_w",
    name: { de: "Wälzkreisdurchmesser", en: "Working pitch diameter" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960"],
    related: ["a_w", "α_wt", "d"],
    description: {
      de: "Die Kreise, auf denen die beiden Räder im Betrieb schlupffrei abwälzen: d_w1 + d_w2 = 2·a_w. Nur paarweise definiert.",
      en: "The circles on which the meshing pair rolls without slip: d_w1 + d_w2 = 2·a_w. Defined only for a pair.",
    },
  },
  {
    symbol: "d_Na",
    name: { de: "Nutzkopfkreis", en: "Usable tip diameter" },
    unit: "mm",
    category: "macro",
    norms: ["ISO 21771"],
    related: ["d_a", "ε_α"],
    description: {
      de: "Ende des nutzbaren Evolventenbereichs am Kopf (vor dem Kopfkantenbruch). Begrenzt zusammen mit dem Nutzfußkreis des Gegenrads die aktive Eingriffsstrecke und damit ε_α.",
      en: "End of the usable involute at the tip (before the edge chamfer). Together with the mating gear's usable root circle it limits the active path of contact and thus ε_α.",
    },
  },
  {
    symbol: "d_Nf",
    name: { de: "Nutzfußkreis", en: "Usable root diameter" },
    unit: "mm",
    category: "macro",
    norms: ["ISO 21771"],
    related: ["d_Ff", "ε_α"],
    description: {
      de: "Tiefster Punkt, den der Kopf des Gegenrads auf der Flanke tatsächlich berührt. Muss oberhalb des Fußformkreises d_Ff liegen, sonst drückt das Gegenrad in die Fußkurve (Eingriffsstörung).",
      en: "Deepest point on the flank the mating tip actually touches. Must lie above the root form circle d_Ff, otherwise the mating gear presses into the fillet (interference).",
    },
  },
  {
    symbol: "d_Ff",
    name: { de: "Fußformkreis", en: "Root form diameter" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["d_f", "ρ_F", "d_Nf"],
    description: {
      de: "Übergangspunkt Evolvente → Fußkurve: Hier endet die nutzbare Flanke und die Fußausrundung beginnt. Optimierte Fußkurven (Ellipse, Bézier, bionisch) setzen genau an diesem Punkt tangential an.",
      en: "Transition involute → root fillet: the usable flank ends here and the fillet begins. Optimized fillets (elliptic, Bézier, bionic) attach tangentially exactly at this point.",
    },
  },
  {
    symbol: "s_n",
    name: { de: "Zahndicke (Normal)", en: "Tooth thickness (normal)" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960", "DIN 3967"],
    related: ["x", "j_n", "p_n"],
    description: {
      de: "Zahndicke am Teilkreis; wächst mit positiver Profilverschiebung. Die Fertigung zieht Zahndickenabmaße (DIN 3967) ab, damit im Betrieb Flankenspiel j_n entsteht.",
      en: "Tooth thickness on the reference circle; grows with positive profile shift. Manufacturing subtracts thickness allowances (DIN 3967) so that backlash j_n exists in operation.",
    },
  },
  {
    symbol: "p_n",
    name: { de: "Teilung (Normal)", en: "Normal pitch" },
    unit: "mm",
    category: "macro",
    norms: ["DIN 3960"],
    related: ["m_n", "f_pt"],
    description: {
      de: "Abstand gleicher Flanken benachbarter Zähne: p_n = π·m_n. Ihre Fertigungsabweichungen (f_pt, F_p) regen Schwingungen an und stecken deshalb im Dynamikfaktor K_V.",
      en: "Spacing of like flanks of adjacent teeth: p_n = π·m_n. Its manufacturing deviations (f_pt, F_p) excite vibrations and therefore enter the dynamic factor K_V.",
    },
  },
  {
    symbol: "ε_α",
    name: { de: "Profilüberdeckung", en: "Transverse contact ratio" },
    unit: "–",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["d_Na", "α_wt", "ε_γ"],
    description: {
      de: "Mittlere Zahl gleichzeitig tragender Zahnpaare im Stirnschnitt (>1 nötig). Höhere Überdeckung verteilt die Last auf mehr Zähne — senkt die Fußspannung des Einzelzahns und die Anregung.",
      en: "Average number of tooth pairs in contact in the transverse plane (>1 required). Higher contact ratio spreads load over more teeth — lowering single-tooth root stress and excitation.",
    },
  },
  {
    symbol: "ε_β",
    name: { de: "Sprungüberdeckung", en: "Overlap ratio" },
    unit: "–",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["β", "b", "ε_γ"],
    description: {
      de: "Überdeckungsanteil aus der Schrägung: ε_β = b·sin β/(π·m_n). Bei Geradverzahnung 0; die Gesamtüberdeckung ist ε_γ = ε_α + ε_β.",
      en: "Contact-ratio share from the helix: ε_β = b·sin β/(π·m_n). Zero for spur gears; the total contact ratio is ε_γ = ε_α + ε_β.",
    },
  },
  {
    symbol: "ε_γ",
    name: { de: "Gesamtüberdeckung", en: "Total contact ratio" },
    unit: "–",
    category: "macro",
    norms: ["DIN 3960", "ISO 21771"],
    related: ["ε_α", "ε_β"],
    description: {
      de: "Summe aus Profil- und Sprungüberdeckung — das Maß dafür, wie gleichmäßig die Last über den Eingriff wandert.",
      en: "Sum of transverse and overlap contact ratios — the measure of how evenly load transfers through the mesh.",
    },
  },
  {
    symbol: "j_n",
    name: { de: "Flankenspiel", en: "Backlash" },
    unit: "µm",
    category: "macro",
    norms: ["DIN 3967", "DIN 3964"],
    related: ["s_n", "a_w"],
    description: {
      de: "Spiel zwischen den Rückflanken im Eingriff. Entsteht aus Zahndickenabmaßen (DIN 3967) und Achsabstandstoleranzen (DIN 3964); Kunststoffräder brauchen zusätzlich Reserve für Quellen und Wärmedehnung. (Toleranz-Workstream: Ausblick.)",
      en: "Play between the non-driving flanks. Created by tooth-thickness allowances (DIN 3967) and centre-distance tolerances (DIN 3964); plastic gears need extra reserve for swelling and thermal expansion. (Tolerance workstream: outlook.)",
    },
  },
  // ------------------------------------------------------------------ tool / basic rack
  {
    symbol: "h_aP0",
    name: { de: "Werkzeug-Kopfhöhenfaktor", en: "Tool addendum factor" },
    unit: "·m_n",
    category: "tool",
    norms: ["DIN 3972", "ISO 53", "DIN 867"],
    related: ["d_f", "ρ_aP0", "ρ_F"],
    description: {
      de: "Kopfhöhe des Werkzeugs (z. B. 1,25·m_n bei DIN 3972 I). Der Werkzeugkopf schneidet den FUSS des Rads: Größeres h_aP0 macht die Lücke tiefer (kleineres d_f) und schafft Platz für eine größere Fußrundung.",
      en: "Tool addendum (e.g. 1.25·m_n for DIN 3972 I). The tool tip cuts the gear ROOT: larger h_aP0 deepens the gap (smaller d_f) and makes room for a larger fillet.",
    },
  },
  {
    symbol: "h_fP0",
    name: { de: "Werkzeug-Fußhöhenfaktor", en: "Tool dedendum factor" },
    unit: "·m_n",
    category: "tool",
    norms: ["DIN 3972", "ISO 53"],
    related: ["d_a", "d_Na"],
    description: {
      de: "Fußhöhe des Werkzeugprofils — begrenzt den KOPF des erzeugten Rads (inkl. Kopfkantenbruch bei DIN 3972 II/III). Bestimmt zusammen mit x den nutzbaren Kopfkreis d_Na.",
      en: "Tool dedendum — limits the TIP of the generated gear (incl. edge chamfer for DIN 3972 II/III). Together with x it sets the usable tip diameter d_Na.",
    },
  },
  {
    symbol: "ρ_aP0",
    name: { de: "Werkzeug-Kopfrundungsradius", en: "Tool tip radius" },
    unit: "·m_n",
    category: "tool",
    norms: ["DIN 3972", "ISO 53", "DIN 3960"],
    related: ["ρ_F", "σ_F", "h_aP0"],
    description: {
      de: "Rundung der Werkzeug-Kopfkante. Sie WÄLZT die Fußkurve (Trochoide) ins Rad — neben x der stärkste Hebel auf die Fußspannung σ_F: größerer Radius = sanftere Kerbe. ISO 53-A: 0,38·m_n.",
      en: "Rounding of the tool tip edge. It GENERATES the root fillet (trochoid) — besides x the strongest lever on root stress σ_F: larger radius = milder notch. ISO 53-A: 0.38·m_n.",
    },
  },
  {
    symbol: "Bezugsprofil",
    name: { de: "Bezugsprofil (Preset)", en: "Basic rack profile (preset)" },
    unit: "–",
    category: "tool",
    norms: ["DIN 867", "ISO 53", "DIN 3972"],
    related: ["h_aP0", "h_fP0", "ρ_aP0", "α_n"],
    description: {
      de: "Genormte Werkzeuggeometrie als Satz (α_n, h_aP0, h_fP0, ρ_aP0): ISO 53 Profile A–D, DIN 3972 Bezugsprofile I–III (Vor-/Fertigverzahnen). In der Auslegung als Preset wählbar und frei überschreibbar.",
      en: "Standardized tool geometry as a set (α_n, h_aP0, h_fP0, ρ_aP0): ISO 53 profiles A–D, DIN 3972 racks I–III (roughing/finishing). Selectable as a preset in the design panel and freely editable.",
    },
  },
  {
    symbol: "Protuberanz",
    name: { de: "Protuberanzwerkzeug", en: "Protuberance tool" },
    unit: "–",
    category: "tool",
    norms: ["DIN 3960 Anh. A", "DIN 3972"],
    related: ["ρ_aP0", "d_Ff"],
    description: {
      de: "Werkzeug mit vorstehender Kopfkante: schneidet einen Freischnitt unter die Flanke, damit beim Schleifen keine Schleifkerbe im Fuß entsteht. Geplanter Erweiterungspunkt (Ausblick im Werkzeugmodell).",
      en: "Tool with a protruding tip: cuts an undercut relief below the flank so grinding leaves no notch in the root. Planned extension point of the tool model (outlook).",
    },
  },
  {
    symbol: "k",
    name: { de: "Kopfkantenbruch", en: "Tip edge chamfer" },
    unit: "mm",
    category: "tool",
    norms: ["DIN 3972", "ISO 21771"],
    related: ["d_a", "d_Na"],
    description: {
      de: "Gebrochene Kopfkante zwischen Nutzkopfkreis d_Na und Kopfkreis d_a (werkzeugerzeugt). Entschärft den Kopfeingriff; im Mesh bildet sie die Kopf-Randschicht sauber ab.",
      en: "Chamfered tip edge between d_Na and d_a (tool-generated). Softens tip engagement; the mesh resolves it as a clean tip boundary layer.",
    },
  },
  // ------------------------------------------------------------------ tooth form & fillets
  {
    symbol: "ρ_F",
    name: { de: "Fußrundungsradius", en: "Root fillet radius" },
    unit: "mm",
    category: "toothform",
    norms: ["ISO 6336-3", "DIN 3990"],
    related: ["ρ_aP0", "σ_F", "Y_S", "d_Ff"],
    description: {
      de: "Ersatz-Krümmungsradius der Fußkurve am 30°-Tangentenpunkt — die Kerbschärfe des Zahnfußes. Geht direkt in den Spannungskorrekturfaktor Y_S ein; die Workbench zeichnet die Standardkurve als ρ_F-Bogen tangential an Flanke und Fußkreis.",
      en: "Equivalent curvature radius of the fillet at the 30° tangent point — the notch sharpness of the root. Feeds directly into the stress correction factor Y_S; the workbench draws the standard curve as a ρ_F arc tangent to flank and root circle.",
    },
  },
  {
    symbol: "Trochoide",
    name: { de: "Werkzeug-Trochoide", en: "Tool trochoid" },
    unit: "–",
    category: "toothform",
    norms: ["DIN 3960", "ISO 21771 §7"],
    related: ["ρ_aP0", "ρ_F", "x"],
    description: {
      de: "Die exakte, vom abwälzenden Werkzeugkopf erzeugte Fußkurve. Referenzgeometrie für geschnittene Räder — in Zahnform und Mesh als Strategie „Werkzeug-Trochoide“ wählbar.",
      en: "The exact root curve generated by the rolling tool tip. Reference geometry for cut gears — selectable as the “tool trochoid” strategy in tooth form and mesh.",
    },
  },
  {
    symbol: "e_f",
    name: { de: "Ellipsen-Fußpunktfaktor", en: "Elliptic root-point factor" },
    unit: "·m_n",
    category: "toothform",
    norms: ["Kassem AGMA 22FTM13"],
    related: ["ρ_F", "σ_F", "c"],
    description: {
      de: "Formparameter der elliptischen Fußkurve: verschiebt ihren Scheitel radial (d_f,e = d_f + e_f·m_n; negativ = tiefer). Tiefere, gestrecktere Ellipsen senken σ_F um typ. 10–24 %, brauchen aber den Freigang-Check gegen den Gegenrad-Kopf.",
      en: "Shape parameter of the elliptic fillet: shifts its apex radially (d_f,e = d_f + e_f·m_n; negative = deeper). Deeper, stretched ellipses cut σ_F by typ. 10–24 % but require the clearance check against the mating tip.",
    },
  },
  {
    symbol: "Be",
    name: { de: "Bézier-Faktor", en: "Bézier factor" },
    unit: "–",
    category: "toothform",
    norms: ["Roth/Opferkuch", "Voith"],
    related: ["d_Ff", "σ_F", "c"],
    description: {
      de: "Steuert die Kontrollpunkt-Länge der kubischen Bézier-Fußkurve zwischen den beiden d_Ff-Punkten einer Lücke (Optimum ≈ 0,57; robust 0,46–0,81). Nutzt die volle Lückentiefe — deshalb läuft sie im Plot sichtbar tiefer als der ρ_F-Bogen.",
      en: "Scales the control-point length of the cubic Bézier fillet between the two d_Ff junctions of a gap (optimum ≈ 0.57; robust 0.46–0.81). Uses the full gap depth — hence it visibly runs deeper than the ρ_F arc in the plot.",
    },
  },
  {
    symbol: "γ_b",
    name: { de: "Keilwinkel (bionisch)", en: "Wedge angle (bionic)" },
    unit: "°",
    category: "toothform",
    norms: ["Mattheck (Zugdreiecke)", "Voith 2009"],
    related: ["b_f", "σ_F"],
    description: {
      de: "Anstellwinkel der Zugdreieck-Kurve am d_Ff-Anschluss der bionischen Fußkurve (Vorgabe: Kassem-Regel aus z und α). Steilere Winkel ziehen die Kurve flacher in die Lücke.",
      en: "Attachment angle of the tension-triangle curve at the d_Ff junction of the bionic fillet (default: Kassem's rule from z and α). Steeper angles pull the curve flatter into the gap.",
    },
  },
  {
    symbol: "b_f",
    name: { de: "Bogenfaktor (bionisch)", en: "Arc factor (bionic)" },
    unit: "–",
    category: "toothform",
    norms: ["Voith 2009"],
    related: ["γ_b", "σ_F"],
    description: {
      de: "Skaliert den zentralen Bodenbogen der bionischen Fußkurve relativ zur Lückenweite (empfohlen 0,3–0,4). Der Bogen setzt auf dem Fußkreis auf.",
      en: "Scales the central bottom arc of the bionic fillet relative to the gap width (recommended 0.3–0.4). The arc bottoms on the root circle.",
    },
  },
  {
    symbol: "c",
    name: { de: "Freigang (Fußkurve)", en: "Root clearance (fillet)" },
    unit: "mm",
    category: "toothform",
    norms: ["DIN 3960"],
    related: ["d_a", "e_f", "Be", "d_Nf"],
    description: {
      de: "Kleinster radialer Abstand zwischen Fußkurve und der Bahn des Gegenrad-Kopfes beim Abwälzen. Negativ = Eingriffsstörung — jede optimierte Fußkurve wird deshalb vor Mesh/Deck automatisch dagegen geprüft.",
      en: "Smallest radial distance between the fillet and the mating tip's rolling path. Negative = interference — every optimized fillet is therefore checked automatically before mesh/deck.",
    },
  },
  {
    symbol: "Unterschnitt",
    name: { de: "Unterschnitt", en: "Undercut" },
    unit: "–",
    category: "toothform",
    norms: ["DIN 3960 (3.6.06)"],
    related: ["x", "z", "d_Ff"],
    description: {
      de: "Bei kleinen Zähnezahlen/negativem x schneidet der Werkzeugkopf in die Evolvente und höhlt den Fuß aus — schwächt den Zahn und kappt die nutzbare Flanke. Die Geometrieprüfung warnt anhand der Mindest-Profilverschiebung.",
      en: "At low tooth counts/negative x the tool tip cuts into the involute and hollows the root — weakening the tooth and truncating the usable flank. The geometry check warns via the minimum profile shift.",
    },
  },
  // ------------------------------------------------------------------ micro geometry
  {
    symbol: "C_a",
    name: { de: "Kopfrücknahme", en: "Tip relief" },
    unit: "µm",
    category: "micro",
    norms: ["ISO 21771 §6"],
    related: ["ε_α", "K_V", "C_f"],
    description: {
      de: "Materialrücknahme am Zahnkopf: kompensiert die lastbedingte Verformung beim Ein-/Austritt (weniger Eingriffsstoß, Geräusch). Pro Flanke einstellbar — unterschiedliche Zug-/Schubflanken heben die Spiegelsymmetrie des FE-Netzes auf.",
      en: "Material relief at the tooth tip: compensates load deflection at engagement entry/exit (less mesh impact, noise). Set per flank — differing drive/coast flanks drop the FE mesh's mirror symmetry.",
    },
  },
  {
    symbol: "C_f",
    name: { de: "Fußrücknahme", en: "Root relief" },
    unit: "µm",
    category: "micro",
    norms: ["ISO 21771 §6"],
    related: ["C_a"],
    description: {
      de: "Gegenstück zur Kopfrücknahme am Flankenfuß — gleiche Wirkung auf den Eingriffsbeginn, seltener verwendet (der Gegenrad-Kopf trifft hier zuerst).",
      en: "Counterpart of tip relief at the flank root — same effect on engagement start, used less often (the mating tip lands here first).",
    },
  },
  {
    symbol: "C_β",
    name: { de: "Breitenballigkeit", en: "Lead crowning" },
    unit: "µm",
    category: "micro",
    norms: ["ISO 21771 §6"],
    related: ["b", "f_Hβ", "K_Fβ"],
    description: {
      de: "Ballige Flankenlinie über der Zahnbreite: zentriert das Tragbild und fängt Wellen-Schiefstellungen ab. Reduziert den Breitenlastfaktor K_Fβ.",
      en: "Crowned tooth trace over the face width: centres the contact pattern and absorbs shaft misalignment. Reduces the face load factor K_Fβ.",
    },
  },
  {
    symbol: "f_Hα",
    name: { de: "Profilwinkelkorrektur", en: "Profile slope modification" },
    unit: "µm",
    category: "micro",
    norms: ["ISO 21771 §6"],
    related: ["C_a", "F_α"],
    description: {
      de: "Bewusste Neigung des Profils über der Eingriffsstrecke (Korrektur) — gleicht z. B. lastbedingte Eingriffswinkeländerungen aus. Als Abweichung heißt dieselbe Größe F_α/f_Hα in ISO 1328-1.",
      en: "Deliberate slope of the profile over the path of contact (modification) — e.g. to offset load-induced pressure-angle change. As a deviation the same quantity appears as F_α/f_Hα in ISO 1328-1.",
    },
  },
  {
    symbol: "f_Hβ",
    name: { de: "Flankenlinien-Winkelkorrektur", en: "Helix slope modification" },
    unit: "µm",
    category: "micro",
    norms: ["ISO 21771 §6"],
    related: ["C_β", "K_Fβ"],
    description: {
      de: "Bewusste Schränkung der Flankenlinie über der Breite — kompensiert vorhersehbare Verlagerungen unter Last (Gehäuse-/Wellenverformung).",
      en: "Deliberate skew of the tooth trace over the width — compensates predictable load-induced displacements (housing/shaft deflection).",
    },
  },
  // ------------------------------------------------------------------ tolerances
  {
    symbol: "Q",
    name: { de: "Verzahnungsqualität", en: "Gear accuracy grade" },
    unit: "–",
    category: "tolerance",
    norms: ["ISO 1328-1", "DIN 3961"],
    related: ["f_pt", "F_p", "K_V"],
    description: {
      de: "Qualitätsstufe der Verzahnung (kleiner = genauer). Legt alle Einzeltoleranzen (Teilung, Profil, Flankenlinie, Rundlauf) fest und geht über die Teilungsabweichung in den Dynamikfaktor K_V ein.",
      en: "Accuracy grade (lower = more accurate). Sets all individual tolerances (pitch, profile, helix, runout) and enters the dynamic factor K_V via the pitch deviation.",
    },
  },
  {
    symbol: "f_pt",
    name: { de: "Teilungs-Einzelabweichung", en: "Single pitch deviation" },
    unit: "µm",
    category: "tolerance",
    norms: ["ISO 1328-1"],
    related: ["Q", "K_V", "p_n"],
    description: {
      de: "Abweichung einer einzelnen Teilung vom Sollwert — die wichtigste Anregungsquelle für Schwingungen im Eingriff und damit Treiber des Dynamikfaktors K_V.",
      en: "Deviation of a single pitch from nominal — the main excitation source for mesh vibration and thus the driver of the dynamic factor K_V.",
    },
  },
  {
    symbol: "F_p",
    name: { de: "Teilungs-Gesamtabweichung", en: "Total cumulative pitch deviation" },
    unit: "µm",
    category: "tolerance",
    norms: ["ISO 1328-1"],
    related: ["f_pt", "F_r"],
    description: {
      de: "Aufsummierte Teilungsabweichung über den ganzen Umfang — beschreibt niederfrequente Drehwegfehler (Taumeln, Exzentrizität der Verzahnung).",
      en: "Accumulated pitch deviation around the full circumference — describes low-frequency transmission error (wobble, eccentricity of the gearing).",
    },
  },
  {
    symbol: "F_α",
    name: { de: "Profil-Gesamtabweichung", en: "Total profile deviation" },
    unit: "µm",
    category: "tolerance",
    norms: ["ISO 1328-1"],
    related: ["Q", "f_Hα"],
    description: {
      de: "Bandbreite der Ist-Flanke um das Soll-Profil über die Eingriffsstrecke. Große Werte verschmieren den Eingriff (Traganteil, Geräusch).",
      en: "Band of the actual flank around the target profile along the path of contact. Large values smear the mesh (contact share, noise).",
    },
  },
  {
    symbol: "F_β",
    name: { de: "Flankenlinien-Gesamtabweichung", en: "Total helix deviation" },
    unit: "µm",
    category: "tolerance",
    norms: ["ISO 1328-1"],
    related: ["Q", "f_Hβ", "K_Fβ"],
    description: {
      de: "Bandbreite der Ist-Flankenlinie über der Zahnbreite — entscheidet zusammen mit der Achslage, wie gleichmäßig die Last über b verteilt ist (K_Fβ).",
      en: "Band of the actual tooth trace over the face width — together with shaft alignment it decides how evenly load spreads over b (K_Fβ).",
    },
  },
  {
    symbol: "F_r",
    name: { de: "Rundlaufabweichung", en: "Runout" },
    unit: "µm",
    category: "tolerance",
    norms: ["ISO 1328-1", "ISO/TR 10064"],
    related: ["F_p", "j_n"],
    description: {
      de: "Exzentrizität der Verzahnung zur Drehachse (Messkugel-Methode nach ISO/TR 10064). Moduliert Spiel und Teilungsfehler einmal pro Umdrehung.",
      en: "Eccentricity of the gearing about the rotation axis (ball-probe method per ISO/TR 10064). Modulates backlash and pitch error once per revolution.",
    },
  },
  {
    symbol: "A_sn",
    name: { de: "Zahndickenabmaß", en: "Tooth thickness allowance" },
    unit: "µm",
    category: "tolerance",
    norms: ["DIN 3967"],
    related: ["s_n", "j_n"],
    description: {
      de: "Gezieltes Dünnerfertigen der Zähne (Abmaßreihen nach DIN 3967), damit die Paarung Flankenspiel bekommt. Geplanter Toleranz-Workstream (Ausblick).",
      en: "Deliberate thinning of the teeth (allowance series per DIN 3967) so the pair gets backlash. Planned tolerance workstream (outlook).",
    },
  },
  // ------------------------------------------------------------------ capacity & dynamics
  {
    symbol: "σ_F",
    name: { de: "Zahnfußspannung", en: "Tooth root stress" },
    unit: "MPa",
    category: "capacity",
    norms: ["ISO 6336-3", "DIN 3990", "VDI 2736"],
    related: ["ρ_F", "Y_F", "Y_S", "F_t", "S_F"],
    description: {
      de: "Biege-/Kerbspannung in der Fußausrundung — die zentrale Größe dieser Arbeit. Normverfahren: F_t·Faktoren (Y_F, Y_S, …); hier zusätzlich direkt per FE (2D-Schnelllöser für Vergleiche, 3D-Abwälzmodell als Referenz). Maximum wandert bei optimierten Fußkurven entlang der Kurve.",
      en: "Bending/notch stress in the root fillet — the central quantity of this thesis. Standard route: F_t times factors (Y_F, Y_S, …); here additionally direct FE (2D quick solver for comparisons, 3D rolling model as reference). With optimized fillets the maximum migrates along the curve.",
    },
  },
  {
    symbol: "σ_FP",
    name: { de: "zulässige Fußspannung", en: "Permissible root stress" },
    unit: "MPa",
    category: "capacity",
    norms: ["VDI 2736", "ISO 6336-3"],
    related: ["σ_F", "S_F"],
    description: {
      de: "Werkstoffgrenze für die Fußspannung. Bei Kunststoff stark temperatur- und lebensdauerabhängig (VDI 2736 Wöhlerlinien); der Vergleich σ_F ≤ σ_FP/S_F liefert die Auslegung.",
      en: "Material limit for root stress. For plastics strongly temperature- and life-dependent (VDI 2736 S-N data); the check σ_F ≤ σ_FP/S_F drives the design.",
    },
  },
  {
    symbol: "Y_F",
    name: { de: "Formfaktor", en: "Form factor" },
    unit: "–",
    category: "capacity",
    norms: ["ISO 6336-3", "DIN 3990"],
    related: ["σ_F", "Y_S", "x"],
    description: {
      de: "Erfasst die Zahnform (Hebelarm und Fußdicke am 30°-Punkt) in der Norm-Fußspannung. Gilt nur für werkzeugerzeugte Standardfüße — für optimierte Fußkurven ersetzt die FE-Rechnung die Y-Faktoren.",
      en: "Captures the tooth shape (lever arm and root chord at the 30° point) in the standard root stress. Valid only for tool-generated standard roots — for optimized fillets the FE computation replaces the Y factors.",
    },
  },
  {
    symbol: "Y_S",
    name: { de: "Spannungskorrekturfaktor", en: "Stress correction factor" },
    unit: "–",
    category: "capacity",
    norms: ["ISO 6336-3", "DIN 3990"],
    related: ["ρ_F", "Y_F", "σ_F"],
    description: {
      de: "Kerbwirkungsfaktor des Zahnfußes: wächst, wenn die Fußrundung ρ_F schärfer wird. Zusammen mit Y_F übersetzt er die Nennbiegung in die örtliche Fußspannung.",
      en: "Notch factor of the tooth root: grows as the fillet ρ_F sharpens. Together with Y_F it converts nominal bending into local root stress.",
    },
  },
  {
    symbol: "Y_ε",
    name: { de: "Überdeckungsfaktor (Fuß)", en: "Contact ratio factor (root)" },
    unit: "–",
    category: "capacity",
    norms: ["DIN 3990", "VDI 2736"],
    related: ["ε_α", "σ_F"],
    description: {
      de: "Rechnet die Fußspannung vom Kraftangriff am Kopf auf den maßgebenden äußeren Einzeleingriffspunkt um — höhere Überdeckung entlastet den Einzelzahn.",
      en: "Converts root stress from tip loading to the decisive outer single-contact point — higher contact ratio unloads the single tooth.",
    },
  },
  {
    symbol: "K_A",
    name: { de: "Anwendungsfaktor", en: "Application factor" },
    unit: "–",
    category: "capacity",
    norms: ["ISO 6336-1", "DIN 3990"],
    related: ["K_V", "σ_F", "M₂"],
    description: {
      de: "Pauschale für äußere Stöße/Ungleichförmigkeit der Arbeitsmaschine (Betriebsweise). Multipliziert das Nennmoment, bevor Verzahnungsfaktoren wirken.",
      en: "Blanket factor for external shocks/irregularity of the driven machine (duty). Multiplies nominal torque before any gearing factors apply.",
    },
  },
  {
    symbol: "K_V",
    name: { de: "Dynamikfaktor", en: "Dynamic factor" },
    unit: "–",
    category: "capacity",
    norms: ["ISO 6336-1"],
    related: ["f_pt", "Q", "ε_γ", "K_A"],
    description: {
      de: "Innere dynamische Zusatzkräfte aus dem Eingriff selbst: wächst mit Umfangsgeschwindigkeit und Teilungsfehlern (Qualität Q), sinkt mit Überdeckung. Das Dynamik-Panel zeigt die ISO-6336-1-Methode B.",
      en: "Internal dynamic mesh forces: grows with pitch-line velocity and pitch errors (grade Q), drops with contact ratio. The dynamics panel implements ISO 6336-1 method B.",
    },
  },
  {
    symbol: "K_Fβ",
    name: { de: "Breitenlastfaktor (Fuß)", en: "Face load factor (root)" },
    unit: "–",
    category: "capacity",
    norms: ["ISO 6336-1"],
    related: ["F_β", "C_β", "b"],
    description: {
      de: "Ungleichmäßige Lastverteilung über die Zahnbreite (Schiefstellung, Verformung, F_β). Balligkeit C_β wirkt dagegen. Multipliziert die örtliche Fußbelastung.",
      en: "Uneven load distribution across the face width (misalignment, deflection, F_β). Crowning C_β counteracts it. Multiplies the local root loading.",
    },
  },
  {
    symbol: "S_F",
    name: { de: "Sicherheit Zahnfuß", en: "Root safety factor" },
    unit: "–",
    category: "capacity",
    norms: ["VDI 2736", "ISO 6336-3"],
    related: ["σ_F", "σ_FP"],
    description: {
      de: "S_F = σ_FP/σ_F — muss über der geforderten Mindestsicherheit liegen (VDI 2736: typ. 1,25 für Ermüdung; statische Spitzenlast separat gegen die Streckgrenze).",
      en: "S_F = σ_FP/σ_F — must exceed the required minimum (VDI 2736: typ. 1.25 for fatigue; static peak load checked separately against yield).",
    },
  },
  {
    symbol: "F_t",
    name: { de: "Umfangskraft", en: "Tangential force" },
    unit: "N",
    category: "capacity",
    norms: ["ISO 6336-1", "VDI 2736"],
    related: ["M₂", "d", "σ_F"],
    description: {
      de: "Nutzkraft am Wälzkreis: F_t = 2000·T/d (T in N·m, d in mm). Eingangsgröße aller Tragfähigkeitsnachweise und Basis der FE-Last.",
      en: "Useful force at the pitch circle: F_t = 2000·T/d (T in N·m, d in mm). Input of all capacity checks and basis of the FE load.",
    },
  },
  {
    symbol: "M₂",
    name: { de: "Moment an Rad 2", en: "Torque at gear 2" },
    unit: "N·mm",
    category: "capacity",
    norms: ["VDI 2736"],
    related: ["u", "F_t", "AMP-TORQUE"],
    description: {
      de: "Lastmoment, ausgedrückt an Rad 2 (kst-E: das Kunststoffrad) — die Eingabegröße des Abwälzmodells. Im Deck wird es über die Zähnezahlen auf das momentenbelastete Rad umgerechnet (T_g = M₂·z_g/z₂) und über AMP-TORQUE aufgebracht.",
      en: "Load torque expressed at gear 2 (kst-E: the plastic wheel) — the rolling model's input. In the deck it is converted via the tooth counts to the torque-loaded gear (T_g = M₂·z_g/z₂) and applied through AMP-TORQUE.",
    },
  },
  {
    symbol: "Marlow",
    name: { de: "Marlow-Hyperelastizität", en: "Marlow hyperelasticity" },
    unit: "–",
    category: "capacity",
    norms: ["Abaqus", "VDI 2736"],
    related: ["σ_F"],
    description: {
      de: "Nichtlineares Materialmodell des Kunststoffrads im FE-Deck: direkt aus der einachsigen Zugkurve (kein Parameterfitting). Stahl bleibt linear-elastisch (E = 210 000 MPa).",
      en: "Nonlinear material model of the plastic wheel in the FE deck: built directly from the uniaxial tension curve (no parameter fitting). Steel stays linear elastic (E = 210,000 MPa).",
    },
  },
  // ------------------------------------------------------------------ FE model & meshing
  {
    symbol: "f_Fuß",
    name: { de: "Netzfeinheit Zahnfuß", en: "Root mesh density" },
    unit: "×",
    category: "fe",
    norms: ["FVA/Stirak-Parametrik"],
    related: ["f_Flanke", "σ_F", "J_min"],
    description: {
      de: "FVA-artiger Dichtefaktor: verfeinert die Randschichten der Fußausrundung durch konforme Kantensplits (Topologie und Qualitäts-Gates bleiben erhalten). Getrennt von der Flanke konvergierbar — der Konvergenz-Schnelltest empfiehlt die Stufe.",
      en: "FVA-style density factor: refines the fillet boundary layers via conformal edge splits (topology and quality gates preserved). Converges separately from the flank — the quick convergence check recommends the level.",
    },
  },
  {
    symbol: "f_Flanke",
    name: { de: "Netzfeinheit Zahnflanke", en: "Flank mesh density" },
    unit: "×",
    category: "fe",
    norms: ["FVA/Stirak-Parametrik"],
    related: ["f_Fuß", "J_min"],
    description: {
      de: "Dichtefaktor der Flanken-Randschicht (Kontaktbereich). Getrennt vom Fuß, damit keine Region überfeinert wird; für Kontaktauswertungen höher wählen.",
      en: "Density factor of the flank boundary layer (contact zone). Separate from the root so neither region over-refines; choose higher for contact evaluations.",
    },
  },
  {
    symbol: "n_breite",
    name: { de: "Schichten über Zahnbreite", en: "Face-width layers" },
    unit: "–",
    category: "fe",
    norms: ["FVA/Stirak-Parametrik"],
    related: ["b", "C3D8R"],
    description: {
      de: "Anzahl Hexaeder-Schichten der Extrusion über die Zahnbreite b. Die Extrusion ist symmetrisch um die Radmitte (z = ±b/2), wie im FVA-Referenzdeck.",
      en: "Number of hex layers of the extrusion across the face width b. The extrusion is symmetric about mid-width (z = ±b/2), like the FVA reference deck.",
    },
  },
  {
    symbol: "Δz",
    name: { de: "Axialversatz", en: "Axial offset" },
    unit: "mm",
    category: "fe",
    norms: ["—"],
    related: ["b", "Rot_Node"],
    description: {
      de: "Verschiebung eines Rads entlang seiner Drehachse gegenüber der mittigen Grundstellung (beide Mittelebenen bei z = 0). Damit lässt sich z. B. ein schmaleres Rad gezielt außermittig auf dem breiteren Ritzel abwälzen lassen.",
      en: "Displacement of one gear along its rotation axis from the centred default (both mid-planes at z = 0). Lets a narrower wheel roll deliberately off-centre on the wider pinion, for example.",
    },
  },
  {
    symbol: "J_min",
    name: { de: "Jacobi-Güte (skaliert)", en: "Scaled Jacobian" },
    unit: "–",
    category: "fe",
    norms: ["ANSA/FVA-Qualitätsmaß"],
    related: ["f_Fuß", "f_Flanke"],
    description: {
      de: "Elementqualität 0…1 (1 = perfektes Rechteck/Quader). Gate des Meshers: keine Zelle unter 0,35 — damit besser als die Referenz (dort 6 Zellen bis hinunter zu 0,24).",
      en: "Element quality 0…1 (1 = perfect rectangle/cuboid). Mesher gate: no cell below 0.35 — better than the reference (which has 6 cells down to 0.24).",
    },
  },
  {
    symbol: "C3D8R",
    name: { de: "Hexaeder-Element (reduziert integriert)", en: "Hex element (reduced integration)" },
    unit: "–",
    category: "fe",
    norms: ["Abaqus"],
    related: ["n_breite", "J_min"],
    description: {
      de: "8-Knoten-Volumenelement mit reduzierter Integration — der Elementtyp des Referenzdecks. Robust und schnell; Hourglass-Kontrolle übernimmt Abaqus.",
      en: "8-node solid with reduced integration — the reference deck's element type. Robust and fast; Abaqus handles hourglass control.",
    },
  },
  {
    symbol: "Rot_Node",
    name: { de: "Rotationsknoten (Rot_Node_Rad1/2)", en: "Rotation node (Rot_Node_Rad1/2)" },
    unit: "–",
    category: "fe",
    norms: ["WoBe-892-Deckaufbau"],
    related: ["Fesselung", "Δz", "AMP-ANGLE", "AMP-TORQUE"],
    description: {
      de: "Referenzknoten auf der Drehachse in Radmitte (z = Mittelebene + Δz): DOF 1–5 gesperrt, DOF 6 frei. Rad 1 sitzt im Ursprung (Prüfstand-Ansicht: links), Rad 2 im Achsabstand (rechts); die Kunststoffseite bekommt den Wälzwinkel (AMP-ANGLE), die Gegenseite das Moment (AMP-TORQUE) — im Viewport als mitbewegte Koordinaten-Triaden sichtbar.",
      en: "Reference node on the rotation axis at mid-width (z = mid-plane + Δz): DOF 1–5 locked, DOF 6 free. Gear 1 sits at the origin (rig view: left), gear 2 at the centre distance (right); the plastic side receives the roll angle (AMP-ANGLE), the other side the torque (AMP-TORQUE) — shown as co-moving triads in the viewport.",
    },
  },
  {
    symbol: "Fesselung",
    name: { de: "Fesselung (Bohrungs-Tie)", en: "Bore tie (Fesselung)" },
    unit: "–",
    category: "fe",
    norms: ["WoBe-892-Deckaufbau"],
    related: ["Rot_Node", "Rigid-Shell"],
    description: {
      de: "Starre Kopplung aller Bohrungsknoten an den Rotationsknoten (*RIGID BODY, TIE) — das Rad hängt drehbar an seiner Welle. Beim Rigid-Shell-Modus ersetzt eine Ganzkörper-Starrheit diese Bohrungskopplung.",
      en: "Rigid coupling of all bore nodes to the rotation node (*RIGID BODY, TIE) — the gear hangs rotatably on its shaft. In rigid-shell mode a whole-body rigidity replaces this bore tie.",
    },
  },
  {
    symbol: "Rigid-Shell",
    name: { de: "Ideal steife Stahlseite", en: "Ideally stiff steel side" },
    unit: "–",
    category: "fe",
    norms: ["Produktentscheid (Mischpaarung)"],
    related: ["Fesselung", "Marlow"],
    description: {
      de: "Materialregel für Mischpaarungen: Die Stahlseite wird als Starrkörper um ihren Rotationsknoten gerechnet (Kontaktflächen bleiben, innere Freiheitsgrade entfallen) — spart massiv Rechenzeit, da die Nachgiebigkeit des Kunststoffs dominiert.",
      en: "Material rule for mixed pairings: the steel side is computed as a rigid body about its rotation node (contact surfaces kept, internal DOFs eliminated) — saves substantial run time since plastic compliance dominates.",
    },
  },
  {
    symbol: "G{g}T{nnn}F{f}",
    name: { de: "Set-Namenskontrakt", en: "Set naming contract" },
    unit: "–",
    category: "fe",
    norms: ["WoBe-892-Postprocessing"],
    related: ["Rot_Node", "n_W"],
    description: {
      de: "Knoten-/Element-Sets je Zahnflanke: g = Rad (1 = Ritzel, 2 = Rad — STE-Reihenfolge, ADR-021), nnn = Zahnnummer, f = Flanke (1/2). Achtung: Das FVA-Referenzdeck nummeriert die Räder umgekehrt; der Deck-Header dokumentiert die Zuordnung.",
      en: "Node/element sets per tooth flank: g = gear (1 = pinion, 2 = wheel — STE order, ADR-021), nnn = tooth number, f = flank (1/2). Note: the FVA reference deck numbers the gears the other way; the deck header documents the mapping.",
    },
  },
  {
    symbol: "n_W",
    name: { de: "Wälzstellungen", en: "Roll positions" },
    unit: "–",
    category: "fe",
    norms: ["WoBe-892 §3.3.1"],
    related: ["AMP-ANGLE", "ε_α"],
    description: {
      de: "Anzahl der über den Abwälzweg ausgewerteten Eingriffsstellungen (Treppenstufen der Winkelkurve). Mehr Stellungen = feinere σ_F-Verläufe über dem Eingriff, längere Rechenzeit.",
      en: "Number of mesh positions evaluated over the roll (steps of the angle staircase). More positions = finer σ_F traces over the engagement, longer run time.",
    },
  },
  {
    symbol: "AMP-ANGLE",
    name: { de: "Winkel-Treppenkurve", en: "Angle staircase amplitude" },
    unit: "rad",
    category: "fe",
    norms: ["WoBe-892-Deckaufbau"],
    related: ["Rot_Node", "n_W", "AMP-TORQUE"],
    description: {
      de: "Amplitudenkurve, die das winkelgetriebene Rad (kst-E: Rad 2, DOF 6) quasi-statisch durch den Abwälzweg dreht: pro Wälzstellung eine gehaltene Stufe, davor eine Setzphase, in der das Moment aufgebaut wird.",
      en: "Amplitude curve that quasi-statically turns the angle-driven gear (kst-E: gear 2, DOF 6) through the roll: one held step per position, preceded by a settle phase while the torque ramps in.",
    },
  },
  {
    symbol: "AMP-TORQUE",
    name: { de: "Momenten-Rampe", en: "Torque ramp amplitude" },
    unit: "–",
    category: "fe",
    norms: ["WoBe-892-Deckaufbau"],
    related: ["M₂", "AMP-ANGLE"],
    description: {
      de: "Amplitudenkurve des Gegenmoments am nicht winkelgetriebenen Rad (kst-E: Rad 1): Rampe während der Setzphase, dann konstant, während AMP-ANGLE abwälzt — so bleibt der Kontakt durchgehend belastet.",
      en: "Amplitude curve of the resisting torque at the non-driven gear (kst-E: gear 1): ramps during the settle phase, then holds while AMP-ANGLE rolls — keeping the contact loaded throughout.",
    },
  },
];
